// generated by `sqlx migrate build-script`
fn main() {
    println!(".cargo:rerun-if-changed=.env");
    // trigger recompilation when a new migration is added
    println!(".cargo:rerun-if-changed=db/migrations");
    println!(".cargo:rerun-if-changed=.cargo");
}