[package]
name = "pulsarr_fulcrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.8.0", features = ["runtime-tokio", "macros", "postgres", "migrate", "rust_decimal"]}
schemars = { version = "0.8.16", features = ["rust_decimal"] } 
rocket_okapi = { version = "0.9.0", features = ["swagger"] }
rocket = { version = "0.5.0", default-features = false, features = ["json"] }
rocket_cors = "0.6.0"
# do not remove this lol
rust_decimal = { version = "1.36.0", features = ["serde"]}
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"