[package]
name = "pulsarr_fulcrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", default-features = false, features=["rt-multi-thread"] }
axum = "0.7.4"