/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetRequest,
  GroupDTO,
} from '../models/index';
import {
    GetRequestFromJSON,
    GetRequestToJSON,
    GroupDTOFromJSON,
    GroupDTOToJSON,
} from '../models/index';

export interface CreateGroupRequest {
    pulsarrApiKey: string;
    groupDTO: GroupDTO;
}

export interface DeleteGroupRequest {
    id: number;
    pulsarrApiKey: string;
}

export interface GetAllGroupsRequest {
    pulsarrApiKey: string;
    getRequest: GetRequest;
}

export interface GetPulsarrGroupRequest {
    id: number;
    pulsarrApiKey: string;
}

export interface JoinGroupRequest {
    groupId: number;
    pulsarrApiKey: string;
}

export interface LeaveGroupRequest {
    groupId: number;
    pulsarrApiKey: string;
}

export interface MyGroupsRequest {
    pulsarrApiKey: string;
}

export interface SearchGroupsRequest {
    pulsarrApiKey: string;
    name?: string | null;
}

export interface UpdateGroupRequest {
    pulsarrApiKey: string;
    groupDTO: GroupDTO;
}

/**
 * 
 */
export class GroupApi extends runtime.BaseAPI {

    /**
     * Create Group
     */
    async createGroupRaw(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDTO>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling createGroup().'
            );
        }

        if (requestParameters['groupDTO'] == null) {
            throw new runtime.RequiredError(
                'groupDTO',
                'Required parameter "groupDTO" was null or undefined when calling createGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupDTOToJSON(requestParameters['groupDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDTOFromJSON(jsonValue));
    }

    /**
     * Create Group
     */
    async createGroup(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDTO> {
        const response = await this.createGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete group
     */
    async deleteGroupRaw(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteGroup().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling deleteGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete group
     */
    async deleteGroup(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all groups
     */
    async getAllGroupsRaw(requestParameters: GetAllGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupDTO>>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling getAllGroups().'
            );
        }

        if (requestParameters['getRequest'] == null) {
            throw new runtime.RequiredError(
                'getRequest',
                'Required parameter "getRequest" was null or undefined when calling getAllGroups().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetRequestToJSON(requestParameters['getRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupDTOFromJSON));
    }

    /**
     * Get all groups
     */
    async getAllGroups(requestParameters: GetAllGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupDTO>> {
        const response = await this.getAllGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the group membership types
     */
    async getMembershipTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/group/membershipTypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the group membership types
     */
    async getMembershipTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getMembershipTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the group privacy types
     */
    async getPrivacyTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/group/privacyTypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the group privacy types
     */
    async getPrivacyTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getPrivacyTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a group by id
     */
    async getPulsarrGroupRaw(requestParameters: GetPulsarrGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPulsarrGroup().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling getPulsarrGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDTOFromJSON(jsonValue));
    }

    /**
     * Get a group by id
     */
    async getPulsarrGroup(requestParameters: GetPulsarrGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDTO> {
        const response = await this.getPulsarrGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Join group
     */
    async joinGroupRaw(requestParameters: JoinGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling joinGroup().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling joinGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/join/{group_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Join group
     */
    async joinGroup(requestParameters: JoinGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.joinGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Leave group
     */
    async leaveGroupRaw(requestParameters: LeaveGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling leaveGroup().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling leaveGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/leave/{group_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Leave group
     */
    async leaveGroup(requestParameters: LeaveGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.leaveGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async myGroupsRaw(requestParameters: MyGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupDTO>>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling myGroups().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/myGroups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupDTOFromJSON));
    }

    /**
     */
    async myGroups(requestParameters: MyGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupDTO>> {
        const response = await this.myGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchGroupsRaw(requestParameters: SearchGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupDTO>>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling searchGroups().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupDTOFromJSON));
    }

    /**
     */
    async searchGroups(requestParameters: SearchGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupDTO>> {
        const response = await this.searchGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update group
     */
    async updateGroupRaw(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDTO>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling updateGroup().'
            );
        }

        if (requestParameters['groupDTO'] == null) {
            throw new runtime.RequiredError(
                'groupDTO',
                'Required parameter "groupDTO" was null or undefined when calling updateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/group/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupDTOToJSON(requestParameters['groupDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDTOFromJSON(jsonValue));
    }

    /**
     * Update group
     */
    async updateGroup(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDTO> {
        const response = await this.updateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
