/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PulsarrGroupModel,
} from '../models/index';
import {
    PulsarrGroupModelFromJSON,
    PulsarrGroupModelToJSON,
} from '../models/index';

export interface AddGroupRequest {
    pulsarrGroupModel: PulsarrGroupModel;
}

export interface DeleteGroupRequest {
    id: number;
}

export interface GetPulsarrGroupRequest {
    id: number;
}

export interface UpdateGroupRequest {
    pulsarrGroupModel: PulsarrGroupModel;
}

/**
 * 
 */
export class GroupApi extends runtime.BaseAPI {

    /**
     * Add a group
     */
    async addGroupRaw(requestParameters: AddGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PulsarrGroupModel>> {
        if (requestParameters['pulsarrGroupModel'] == null) {
            throw new runtime.RequiredError(
                'pulsarrGroupModel',
                'Required parameter "pulsarrGroupModel" was null or undefined when calling addGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/group/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PulsarrGroupModelToJSON(requestParameters['pulsarrGroupModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PulsarrGroupModelFromJSON(jsonValue));
    }

    /**
     * Add a group
     */
    async addGroup(requestParameters: AddGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PulsarrGroupModel> {
        const response = await this.addGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete group
     */
    async deleteGroupRaw(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/group/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete group
     */
    async deleteGroup(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all groups
     */
    async getAllGroupsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PulsarrGroupModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/group/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PulsarrGroupModelFromJSON));
    }

    /**
     * Get all groups
     */
    async getAllGroups(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PulsarrGroupModel>> {
        const response = await this.getAllGroupsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the group privacy types
     */
    async getPrivacyTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/group/privacyTypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the group privacy types
     */
    async getPrivacyTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getPrivacyTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a group by id
     */
    async getPulsarrGroupRaw(requestParameters: GetPulsarrGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PulsarrGroupModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPulsarrGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/group/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PulsarrGroupModelFromJSON(jsonValue));
    }

    /**
     * Get a group by id
     */
    async getPulsarrGroup(requestParameters: GetPulsarrGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PulsarrGroupModel> {
        const response = await this.getPulsarrGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update group
     */
    async updateGroupRaw(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PulsarrGroupModel>> {
        if (requestParameters['pulsarrGroupModel'] == null) {
            throw new runtime.RequiredError(
                'pulsarrGroupModel',
                'Required parameter "pulsarrGroupModel" was null or undefined when calling updateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/group/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PulsarrGroupModelToJSON(requestParameters['pulsarrGroupModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PulsarrGroupModelFromJSON(jsonValue));
    }

    /**
     * Update group
     */
    async updateGroup(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PulsarrGroupModel> {
        const response = await this.updateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
