/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Artist,
  ArtistSearchResponse,
  CoverArtArchive,
  CoverArtInfo,
  Recording,
  RecordingSearchResponse,
  Release,
  ReleaseSearchResponse,
} from '../models/index';
import {
    ArtistFromJSON,
    ArtistToJSON,
    ArtistSearchResponseFromJSON,
    ArtistSearchResponseToJSON,
    CoverArtArchiveFromJSON,
    CoverArtArchiveToJSON,
    CoverArtInfoFromJSON,
    CoverArtInfoToJSON,
    RecordingFromJSON,
    RecordingToJSON,
    RecordingSearchResponseFromJSON,
    RecordingSearchResponseToJSON,
    ReleaseFromJSON,
    ReleaseToJSON,
    ReleaseSearchResponseFromJSON,
    ReleaseSearchResponseToJSON,
} from '../models/index';

export interface GetArtistRequest {
    mbid: string;
}

export interface GetRecordingRequest {
    mbid: string;
}

export interface GetReleaseRequest {
    mbid: string;
}

export interface GetReleaseCoverArtRequest {
    mbid: string;
}

export interface GetReleaseCoverArtInfoRequest {
    mbid: string;
}

export interface GetReleaseGroupCoverArtRequest {
    mbid: string;
}

export interface SearchArtistsRequest {
    query: string;
    limit?: number | null;
    offset?: number | null;
}

export interface SearchRecordingsRequest {
    query: string;
    limit?: number | null;
    offset?: number | null;
}

export interface SearchReleasesRequest {
    query: string;
    limit?: number | null;
    offset?: number | null;
}

/**
 * 
 */
export class MusicBrainzApi extends runtime.BaseAPI {

    /**
     * Get artist by MBID
     */
    async getArtistRaw(requestParameters: GetArtistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Artist>> {
        if (requestParameters['mbid'] == null) {
            throw new runtime.RequiredError(
                'mbid',
                'Required parameter "mbid" was null or undefined when calling getArtist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/artist/{mbid}`.replace(`{${"mbid"}}`, encodeURIComponent(String(requestParameters['mbid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistFromJSON(jsonValue));
    }

    /**
     * Get artist by MBID
     */
    async getArtist(requestParameters: GetArtistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Artist> {
        const response = await this.getArtistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get recording by MBID
     */
    async getRecordingRaw(requestParameters: GetRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Recording>> {
        if (requestParameters['mbid'] == null) {
            throw new runtime.RequiredError(
                'mbid',
                'Required parameter "mbid" was null or undefined when calling getRecording().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/recording/{mbid}`.replace(`{${"mbid"}}`, encodeURIComponent(String(requestParameters['mbid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecordingFromJSON(jsonValue));
    }

    /**
     * Get recording by MBID
     */
    async getRecording(requestParameters: GetRecordingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Recording> {
        const response = await this.getRecordingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get release by MBID
     */
    async getReleaseRaw(requestParameters: GetReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Release>> {
        if (requestParameters['mbid'] == null) {
            throw new runtime.RequiredError(
                'mbid',
                'Required parameter "mbid" was null or undefined when calling getRelease().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/release/{mbid}`.replace(`{${"mbid"}}`, encodeURIComponent(String(requestParameters['mbid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReleaseFromJSON(jsonValue));
    }

    /**
     * Get release by MBID
     */
    async getRelease(requestParameters: GetReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Release> {
        const response = await this.getReleaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get cover art for a release
     */
    async getReleaseCoverArtRaw(requestParameters: GetReleaseCoverArtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoverArtArchive>> {
        if (requestParameters['mbid'] == null) {
            throw new runtime.RequiredError(
                'mbid',
                'Required parameter "mbid" was null or undefined when calling getReleaseCoverArt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/release/{mbid}/cover-art`.replace(`{${"mbid"}}`, encodeURIComponent(String(requestParameters['mbid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoverArtArchiveFromJSON(jsonValue));
    }

    /**
     * Get cover art for a release
     */
    async getReleaseCoverArt(requestParameters: GetReleaseCoverArtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoverArtArchive> {
        const response = await this.getReleaseCoverArtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get cover art info for a release (convenience method with front/back URLs)
     */
    async getReleaseCoverArtInfoRaw(requestParameters: GetReleaseCoverArtInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoverArtInfo>> {
        if (requestParameters['mbid'] == null) {
            throw new runtime.RequiredError(
                'mbid',
                'Required parameter "mbid" was null or undefined when calling getReleaseCoverArtInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/release/{mbid}/cover-art-info`.replace(`{${"mbid"}}`, encodeURIComponent(String(requestParameters['mbid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoverArtInfoFromJSON(jsonValue));
    }

    /**
     * Get cover art info for a release (convenience method with front/back URLs)
     */
    async getReleaseCoverArtInfo(requestParameters: GetReleaseCoverArtInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoverArtInfo> {
        const response = await this.getReleaseCoverArtInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get cover art for a release group
     */
    async getReleaseGroupCoverArtRaw(requestParameters: GetReleaseGroupCoverArtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoverArtArchive>> {
        if (requestParameters['mbid'] == null) {
            throw new runtime.RequiredError(
                'mbid',
                'Required parameter "mbid" was null or undefined when calling getReleaseGroupCoverArt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/release-group/{mbid}/cover-art`.replace(`{${"mbid"}}`, encodeURIComponent(String(requestParameters['mbid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoverArtArchiveFromJSON(jsonValue));
    }

    /**
     * Get cover art for a release group
     */
    async getReleaseGroupCoverArt(requestParameters: GetReleaseGroupCoverArtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoverArtArchive> {
        const response = await this.getReleaseGroupCoverArtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search for artists on MusicBrainz
     */
    async searchArtistsRaw(requestParameters: SearchArtistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistSearchResponse>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchArtists().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/search/artist`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistSearchResponseFromJSON(jsonValue));
    }

    /**
     * Search for artists on MusicBrainz
     */
    async searchArtists(requestParameters: SearchArtistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistSearchResponse> {
        const response = await this.searchArtistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search for recordings on MusicBrainz
     */
    async searchRecordingsRaw(requestParameters: SearchRecordingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecordingSearchResponse>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchRecordings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/search/recording`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecordingSearchResponseFromJSON(jsonValue));
    }

    /**
     * Search for recordings on MusicBrainz
     */
    async searchRecordings(requestParameters: SearchRecordingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecordingSearchResponse> {
        const response = await this.searchRecordingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search for releases on MusicBrainz
     */
    async searchReleasesRaw(requestParameters: SearchReleasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReleaseSearchResponse>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchReleases().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/musicbrainz/search/release`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReleaseSearchResponseFromJSON(jsonValue));
    }

    /**
     * Search for releases on MusicBrainz
     */
    async searchReleases(requestParameters: SearchReleasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReleaseSearchResponse> {
        const response = await this.searchReleasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
