/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetRequest,
  Rating,
  UserProfileResponse,
} from '../models/index';
import {
    GetRequestFromJSON,
    GetRequestToJSON,
    RatingFromJSON,
    RatingToJSON,
    UserProfileResponseFromJSON,
    UserProfileResponseToJSON,
} from '../models/index';

export interface GetProfileRatingsRequest {
    userId: number;
    pulsarrApiKey: string;
    getRequest: GetRequest;
}

export interface GetUserProfileRequest {
    userId: number;
    pulsarrApiKey: string;
}

/**
 * 
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     * Get paginated ratings for a user\'s profile (filtered by visibility)
     */
    async getProfileRatingsRaw(requestParameters: GetProfileRatingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Rating>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getProfileRatings().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling getProfileRatings().'
            );
        }

        if (requestParameters['getRequest'] == null) {
            throw new runtime.RequiredError(
                'getRequest',
                'Required parameter "getRequest" was null or undefined when calling getProfileRatings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/profile/{user_id}/ratings`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetRequestToJSON(requestParameters['getRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingFromJSON));
    }

    /**
     * Get paginated ratings for a user\'s profile (filtered by visibility)
     */
    async getProfileRatings(requestParameters: GetProfileRatingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Rating>> {
        const response = await this.getProfileRatingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a user\'s profile with visibility information
     */
    async getUserProfileRaw(requestParameters: GetUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserProfile().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling getUserProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/profile/{user_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Get a user\'s profile with visibility information
     */
    async getUserProfile(requestParameters: GetUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponse> {
        const response = await this.getUserProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
