/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RatingSystemTemplate,
  RatingSystemTemplateDTO,
} from '../models/index';
import {
    RatingSystemTemplateFromJSON,
    RatingSystemTemplateToJSON,
    RatingSystemTemplateDTOFromJSON,
    RatingSystemTemplateDTOToJSON,
} from '../models/index';

export interface AddTemplateRequest {
    ratingSystemTemplateDTO: RatingSystemTemplateDTO;
}

export interface DeleteTemplateRequest {
    id: number;
}

export interface GetTemplateRequest {
    id: number;
}

export interface UpdateTemplateRequest {
    ratingSystemTemplate: RatingSystemTemplate;
}

/**
 * 
 */
export class RatingSystemTemplateApi extends runtime.BaseAPI {

    /**
     * Create a new rating system template with parameters
     */
    async addTemplateRaw(requestParameters: AddTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystemTemplateDTO>> {
        if (requestParameters['ratingSystemTemplateDTO'] == null) {
            throw new runtime.RequiredError(
                'ratingSystemTemplateDTO',
                'Required parameter "ratingSystemTemplateDTO" was null or undefined when calling addTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating-system-template/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingSystemTemplateDTOToJSON(requestParameters['ratingSystemTemplateDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemTemplateDTOFromJSON(jsonValue));
    }

    /**
     * Create a new rating system template with parameters
     */
    async addTemplate(requestParameters: AddTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystemTemplateDTO> {
        const response = await this.addTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a rating system template
     */
    async deleteTemplateRaw(requestParameters: DeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system-template/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a rating system template
     */
    async deleteTemplate(requestParameters: DeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all rating system templates (with parameters hydrated)
     */
    async getAllTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingSystemTemplateDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system-template/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingSystemTemplateDTOFromJSON));
    }

    /**
     * Get all rating system templates (with parameters hydrated)
     */
    async getAllTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingSystemTemplateDTO>> {
        const response = await this.getAllTemplatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a rating system template by ID (with parameters)
     */
    async getTemplateRaw(requestParameters: GetTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystemTemplateDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system-template/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemTemplateDTOFromJSON(jsonValue));
    }

    /**
     * Get a rating system template by ID (with parameters)
     */
    async getTemplate(requestParameters: GetTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystemTemplateDTO> {
        const response = await this.getTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a rating system template
     */
    async updateTemplateRaw(requestParameters: UpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystemTemplate>> {
        if (requestParameters['ratingSystemTemplate'] == null) {
            throw new runtime.RequiredError(
                'ratingSystemTemplate',
                'Required parameter "ratingSystemTemplate" was null or undefined when calling updateTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating-system-template/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingSystemTemplateToJSON(requestParameters['ratingSystemTemplate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemTemplateFromJSON(jsonValue));
    }

    /**
     * Update a rating system template
     */
    async updateTemplate(requestParameters: UpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystemTemplate> {
        const response = await this.updateTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
