/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RatingDetailModel,
  RatingModel,
} from '../models/index';
import {
    RatingDetailModelFromJSON,
    RatingDetailModelToJSON,
    RatingModelFromJSON,
    RatingModelToJSON,
} from '../models/index';

export interface AddRatingRequest {
    ratingModel: RatingModel;
}

export interface AddRatingDetailRequest {
    ratingDetailModel: RatingDetailModel;
}

export interface DeleteRatingRequest {
    id: number;
}

export interface DeleteRatingDetailRequest {
    id: number;
}

export interface GetRatingRequest {
    id: number;
}

export interface GetRatingDetailRequest {
    id: number;
}

export interface UpdateRatingRequest {
    ratingModel: RatingModel;
}

export interface UpdateRatingDetailRequest {
    ratingDetailModel: RatingDetailModel;
}

/**
 * 
 */
export class RatingApi extends runtime.BaseAPI {

    /**
     * Add rating
     */
    async addRatingRaw(requestParameters: AddRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingModel>> {
        if (requestParameters['ratingModel'] == null) {
            throw new runtime.RequiredError(
                'ratingModel',
                'Required parameter "ratingModel" was null or undefined when calling addRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingModelToJSON(requestParameters['ratingModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingModelFromJSON(jsonValue));
    }

    /**
     * Add rating
     */
    async addRating(requestParameters: AddRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingModel> {
        const response = await this.addRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add rating detail
     */
    async addRatingDetailRaw(requestParameters: AddRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingDetailModel>> {
        if (requestParameters['ratingDetailModel'] == null) {
            throw new runtime.RequiredError(
                'ratingDetailModel',
                'Required parameter "ratingDetailModel" was null or undefined when calling addRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/rating_detail/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingDetailModelToJSON(requestParameters['ratingDetailModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingDetailModelFromJSON(jsonValue));
    }

    /**
     * Add rating detail
     */
    async addRatingDetail(requestParameters: AddRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingDetailModel> {
        const response = await this.addRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete rating
     */
    async deleteRatingRaw(requestParameters: DeleteRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete rating
     */
    async deleteRating(requestParameters: DeleteRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete rating detail
     */
    async deleteRatingDetailRaw(requestParameters: DeleteRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/rating_detail/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete rating detail
     */
    async deleteRatingDetail(requestParameters: DeleteRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all rating details
     */
    async getAllRatingDetailsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingDetailModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/rating_detail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingDetailModelFromJSON));
    }

    /**
     * Get all rating details
     */
    async getAllRatingDetails(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingDetailModel>> {
        const response = await this.getAllRatingDetailsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all ratings
     */
    async getAllRatingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingModelFromJSON));
    }

    /**
     * Get all ratings
     */
    async getAllRatings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingModel>> {
        const response = await this.getAllRatingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a rating by id
     */
    async getRatingRaw(requestParameters: GetRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingModelFromJSON(jsonValue));
    }

    /**
     * Get a rating by id
     */
    async getRating(requestParameters: GetRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingModel> {
        const response = await this.getRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a rating detail by id
     */
    async getRatingDetailRaw(requestParameters: GetRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingDetailModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/rating_detail/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingDetailModelFromJSON(jsonValue));
    }

    /**
     * Get a rating detail by id
     */
    async getRatingDetail(requestParameters: GetRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingDetailModel> {
        const response = await this.getRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update rating
     */
    async updateRatingRaw(requestParameters: UpdateRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingModel>> {
        if (requestParameters['ratingModel'] == null) {
            throw new runtime.RequiredError(
                'ratingModel',
                'Required parameter "ratingModel" was null or undefined when calling updateRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingModelToJSON(requestParameters['ratingModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingModelFromJSON(jsonValue));
    }

    /**
     * Update rating
     */
    async updateRating(requestParameters: UpdateRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingModel> {
        const response = await this.updateRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update rating detail
     */
    async updateRatingDetailRaw(requestParameters: UpdateRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingDetailModel>> {
        if (requestParameters['ratingDetailModel'] == null) {
            throw new runtime.RequiredError(
                'ratingDetailModel',
                'Required parameter "ratingDetailModel" was null or undefined when calling updateRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/rating_detail/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingDetailModelToJSON(requestParameters['ratingDetailModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingDetailModelFromJSON(jsonValue));
    }

    /**
     * Update rating detail
     */
    async updateRatingDetail(requestParameters: UpdateRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingDetailModel> {
        const response = await this.updateRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
