/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRatingDTO,
  PaginatedGroupRatingsRequest,
  Rating,
  RatingDetail,
  RatingDetailResponse,
  UserRatingStats,
} from '../models/index';
import {
    CreateRatingDTOFromJSON,
    CreateRatingDTOToJSON,
    PaginatedGroupRatingsRequestFromJSON,
    PaginatedGroupRatingsRequestToJSON,
    RatingFromJSON,
    RatingToJSON,
    RatingDetailFromJSON,
    RatingDetailToJSON,
    RatingDetailResponseFromJSON,
    RatingDetailResponseToJSON,
    UserRatingStatsFromJSON,
    UserRatingStatsToJSON,
} from '../models/index';

export interface AddRatingRequest {
    pulsarrApiKey: string;
    createRatingDTO: CreateRatingDTO;
}

export interface AddRatingDetailRequest {
    ratingDetail: RatingDetail;
}

export interface DeleteRatingRequest {
    id: number;
}

export interface DeleteRatingDetailRequest {
    id: number;
}

export interface DeleteRatingDetailsByRatingRequest {
    ratingId: number;
    pulsarrApiKey: string;
}

export interface GetExistingRatingRequest {
    groupId: number;
    musicbrainzId: string;
    pulsarrApiKey: string;
}

export interface GetRatingRequest {
    id: number;
}

export interface GetRatingDetailRequest {
    id: number;
}

export interface GetRatingDetailsByRatingRequest {
    ratingId: number;
}

export interface GetRatingsByGroupRequest {
    paginatedGroupRatingsRequest: PaginatedGroupRatingsRequest;
}

export interface GetRatingsByUserRequest {
    pulsarrApiKey: string;
    takeSize?: number | null;
    offset?: number | null;
}

export interface GetUserRatingStatsRequest {
    pulsarrApiKey: string;
}

export interface UpdateRatingRequest {
    pulsarrApiKey: string;
    rating: Rating;
}

export interface UpdateRatingDetailRequest {
    ratingDetail: RatingDetail;
}

/**
 * 
 */
export class RatingApi extends runtime.BaseAPI {

    /**
     * Add rating
     */
    async addRatingRaw(requestParameters: AddRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Rating>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling addRating().'
            );
        }

        if (requestParameters['createRatingDTO'] == null) {
            throw new runtime.RequiredError(
                'createRatingDTO',
                'Required parameter "createRatingDTO" was null or undefined when calling addRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/rating/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRatingDTOToJSON(requestParameters['createRatingDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingFromJSON(jsonValue));
    }

    /**
     * Add rating
     */
    async addRating(requestParameters: AddRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Rating> {
        const response = await this.addRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add rating detail
     */
    async addRatingDetailRaw(requestParameters: AddRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingDetail>> {
        if (requestParameters['ratingDetail'] == null) {
            throw new runtime.RequiredError(
                'ratingDetail',
                'Required parameter "ratingDetail" was null or undefined when calling addRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/rating_detail/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingDetailToJSON(requestParameters['ratingDetail']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingDetailFromJSON(jsonValue));
    }

    /**
     * Add rating detail
     */
    async addRatingDetail(requestParameters: AddRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingDetail> {
        const response = await this.addRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete rating
     */
    async deleteRatingRaw(requestParameters: DeleteRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete rating
     */
    async deleteRating(requestParameters: DeleteRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete rating detail
     */
    async deleteRatingDetailRaw(requestParameters: DeleteRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/rating_detail/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete rating detail
     */
    async deleteRatingDetail(requestParameters: DeleteRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete all rating details for a rating (ownership verified)
     */
    async deleteRatingDetailsByRatingRaw(requestParameters: DeleteRatingDetailsByRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['ratingId'] == null) {
            throw new runtime.RequiredError(
                'ratingId',
                'Required parameter "ratingId" was null or undefined when calling deleteRatingDetailsByRating().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling deleteRatingDetailsByRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/rating/rating_detail/by_rating/{rating_id}`.replace(`{${"rating_id"}}`, encodeURIComponent(String(requestParameters['ratingId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete all rating details for a rating (ownership verified)
     */
    async deleteRatingDetailsByRating(requestParameters: DeleteRatingDetailsByRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteRatingDetailsByRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all rating details
     */
    async getAllRatingDetailsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingDetail>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/rating_detail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingDetailFromJSON));
    }

    /**
     * Get all rating details
     */
    async getAllRatingDetails(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingDetail>> {
        const response = await this.getAllRatingDetailsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all ratings
     */
    async getAllRatingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Rating>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingFromJSON));
    }

    /**
     * Get all ratings
     */
    async getAllRatings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Rating>> {
        const response = await this.getAllRatingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get existing ratings for a specific media item in a group (for re-rating reference)
     */
    async getExistingRatingRaw(requestParameters: GetExistingRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Rating>>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling getExistingRating().'
            );
        }

        if (requestParameters['musicbrainzId'] == null) {
            throw new runtime.RequiredError(
                'musicbrainzId',
                'Required parameter "musicbrainzId" was null or undefined when calling getExistingRating().'
            );
        }

        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling getExistingRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/rating/existing/{group_id}/{musicbrainz_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId']))).replace(`{${"musicbrainz_id"}}`, encodeURIComponent(String(requestParameters['musicbrainzId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingFromJSON));
    }

    /**
     * Get existing ratings for a specific media item in a group (for re-rating reference)
     */
    async getExistingRating(requestParameters: GetExistingRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Rating>> {
        const response = await this.getExistingRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a rating by id
     */
    async getRatingRaw(requestParameters: GetRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Rating>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingFromJSON(jsonValue));
    }

    /**
     * Get a rating by id
     */
    async getRating(requestParameters: GetRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Rating> {
        const response = await this.getRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a rating detail by id
     */
    async getRatingDetailRaw(requestParameters: GetRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/rating_detail/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingDetailFromJSON(jsonValue));
    }

    /**
     * Get a rating detail by id
     */
    async getRatingDetail(requestParameters: GetRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingDetail> {
        const response = await this.getRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get rating details by rating ID
     */
    async getRatingDetailsByRatingRaw(requestParameters: GetRatingDetailsByRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingDetailResponse>>> {
        if (requestParameters['ratingId'] == null) {
            throw new runtime.RequiredError(
                'ratingId',
                'Required parameter "ratingId" was null or undefined when calling getRatingDetailsByRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating/rating_detail/by_rating/{rating_id}`.replace(`{${"rating_id"}}`, encodeURIComponent(String(requestParameters['ratingId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingDetailResponseFromJSON));
    }

    /**
     * Get rating details by rating ID
     */
    async getRatingDetailsByRating(requestParameters: GetRatingDetailsByRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingDetailResponse>> {
        const response = await this.getRatingDetailsByRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get ratings by group IDs
     */
    async getRatingsByGroupRaw(requestParameters: GetRatingsByGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Rating>>> {
        if (requestParameters['paginatedGroupRatingsRequest'] == null) {
            throw new runtime.RequiredError(
                'paginatedGroupRatingsRequest',
                'Required parameter "paginatedGroupRatingsRequest" was null or undefined when calling getRatingsByGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/byGroups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaginatedGroupRatingsRequestToJSON(requestParameters['paginatedGroupRatingsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingFromJSON));
    }

    /**
     * Get ratings by group IDs
     */
    async getRatingsByGroup(requestParameters: GetRatingsByGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Rating>> {
        const response = await this.getRatingsByGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get ratings by authenticated user
     */
    async getRatingsByUserRaw(requestParameters: GetRatingsByUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Rating>>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling getRatingsByUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['takeSize'] != null) {
            queryParameters['take_size'] = requestParameters['takeSize'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/rating/byUser`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingFromJSON));
    }

    /**
     * Get ratings by authenticated user
     */
    async getRatingsByUser(requestParameters: GetRatingsByUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Rating>> {
        const response = await this.getRatingsByUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get rating stats for authenticated user
     */
    async getUserRatingStatsRaw(requestParameters: GetUserRatingStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRatingStats>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling getUserRatingStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/rating/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRatingStatsFromJSON(jsonValue));
    }

    /**
     * Get rating stats for authenticated user
     */
    async getUserRatingStats(requestParameters: GetUserRatingStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRatingStats> {
        const response = await this.getUserRatingStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update rating
     */
    async updateRatingRaw(requestParameters: UpdateRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Rating>> {
        if (requestParameters['pulsarrApiKey'] == null) {
            throw new runtime.RequiredError(
                'pulsarrApiKey',
                'Required parameter "pulsarrApiKey" was null or undefined when calling updateRating().'
            );
        }

        if (requestParameters['rating'] == null) {
            throw new runtime.RequiredError(
                'rating',
                'Required parameter "rating" was null or undefined when calling updateRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['pulsarrApiKey'] != null) {
            headerParameters['pulsarr-api-key'] = String(requestParameters['pulsarrApiKey']);
        }

        const response = await this.request({
            path: `/rating/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingToJSON(requestParameters['rating']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingFromJSON(jsonValue));
    }

    /**
     * Update rating
     */
    async updateRating(requestParameters: UpdateRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Rating> {
        const response = await this.updateRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update rating detail
     */
    async updateRatingDetailRaw(requestParameters: UpdateRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingDetail>> {
        if (requestParameters['ratingDetail'] == null) {
            throw new runtime.RequiredError(
                'ratingDetail',
                'Required parameter "ratingDetail" was null or undefined when calling updateRatingDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating/rating_detail/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingDetailToJSON(requestParameters['ratingDetail']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingDetailFromJSON(jsonValue));
    }

    /**
     * Update rating detail
     */
    async updateRatingDetail(requestParameters: UpdateRatingDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingDetail> {
        const response = await this.updateRatingDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
