/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RatingSystem,
  RatingSystemDTO,
  RatingSystemParameter,
} from '../models/index';
import {
    RatingSystemFromJSON,
    RatingSystemToJSON,
    RatingSystemDTOFromJSON,
    RatingSystemDTOToJSON,
    RatingSystemParameterFromJSON,
    RatingSystemParameterToJSON,
} from '../models/index';

export interface AddRatingSystemRequest {
    ratingSystemDTO: RatingSystemDTO;
}

export interface AddRatingSystemParameterRequest {
    ratingSystemParameter: RatingSystemParameter;
}

export interface DeleteRatingSystemRequest {
    id: number;
}

export interface DeleteRatingSystemParameterRequest {
    id: number;
}

export interface GetRatingSystemRequest {
    id: number;
}

export interface GetRatingSystemParameterRequest {
    id: number;
}

export interface UpdateRatingSystemRequest {
    ratingSystem: RatingSystem;
}

export interface UpdateRatingSystemParameterRequest {
    ratingSystemParameter: RatingSystemParameter;
}

/**
 * 
 */
export class RatingSystemApi extends runtime.BaseAPI {

    /**
     * Add rating system
     */
    async addRatingSystemRaw(requestParameters: AddRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystemDTO>> {
        if (requestParameters['ratingSystemDTO'] == null) {
            throw new runtime.RequiredError(
                'ratingSystemDTO',
                'Required parameter "ratingSystemDTO" was null or undefined when calling addRatingSystem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating-system/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingSystemDTOToJSON(requestParameters['ratingSystemDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemDTOFromJSON(jsonValue));
    }

    /**
     * Add rating system
     */
    async addRatingSystem(requestParameters: AddRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystemDTO> {
        const response = await this.addRatingSystemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add rating system parameter
     */
    async addRatingSystemParameterRaw(requestParameters: AddRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystemParameter>> {
        if (requestParameters['ratingSystemParameter'] == null) {
            throw new runtime.RequiredError(
                'ratingSystemParameter',
                'Required parameter "ratingSystemParameter" was null or undefined when calling addRatingSystemParameter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating-system/parameter/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingSystemParameterToJSON(requestParameters['ratingSystemParameter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemParameterFromJSON(jsonValue));
    }

    /**
     * Add rating system parameter
     */
    async addRatingSystemParameter(requestParameters: AddRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystemParameter> {
        const response = await this.addRatingSystemParameterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete rating system
     */
    async deleteRatingSystemRaw(requestParameters: DeleteRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRatingSystem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete rating system
     */
    async deleteRatingSystem(requestParameters: DeleteRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteRatingSystemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete rating system parameter
     */
    async deleteRatingSystemParameterRaw(requestParameters: DeleteRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRatingSystemParameter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system/parameter/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete rating system parameter
     */
    async deleteRatingSystemParameter(requestParameters: DeleteRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteRatingSystemParameterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all rating system parameters
     */
    async getAllRatingSystemParametersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingSystemParameter>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system/parameter`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingSystemParameterFromJSON));
    }

    /**
     * Get all rating system parameters
     */
    async getAllRatingSystemParameters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingSystemParameter>> {
        const response = await this.getAllRatingSystemParametersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all rating systems
     */
    async getAllRatingSystemsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RatingSystem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RatingSystemFromJSON));
    }

    /**
     * Get all rating systems
     */
    async getAllRatingSystems(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RatingSystem>> {
        const response = await this.getAllRatingSystemsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a rating system by id
     */
    async getRatingSystemRaw(requestParameters: GetRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRatingSystem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemFromJSON(jsonValue));
    }

    /**
     * Get a rating system by id
     */
    async getRatingSystem(requestParameters: GetRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystem> {
        const response = await this.getRatingSystemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a rating system parameter by id
     */
    async getRatingSystemParameterRaw(requestParameters: GetRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystemParameter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRatingSystemParameter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system/parameter/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemParameterFromJSON(jsonValue));
    }

    /**
     * Get a rating system parameter by id
     */
    async getRatingSystemParameter(requestParameters: GetRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystemParameter> {
        const response = await this.getRatingSystemParameterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the master rating types
     */
    async getRatingTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rating-system/ratingTypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the master rating types
     */
    async getRatingTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getRatingTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update rating system
     */
    async updateRatingSystemRaw(requestParameters: UpdateRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystem>> {
        if (requestParameters['ratingSystem'] == null) {
            throw new runtime.RequiredError(
                'ratingSystem',
                'Required parameter "ratingSystem" was null or undefined when calling updateRatingSystem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating-system/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingSystemToJSON(requestParameters['ratingSystem']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemFromJSON(jsonValue));
    }

    /**
     * Update rating system
     */
    async updateRatingSystem(requestParameters: UpdateRatingSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystem> {
        const response = await this.updateRatingSystemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update rating system parameter
     */
    async updateRatingSystemParameterRaw(requestParameters: UpdateRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingSystemParameter>> {
        if (requestParameters['ratingSystemParameter'] == null) {
            throw new runtime.RequiredError(
                'ratingSystemParameter',
                'Required parameter "ratingSystemParameter" was null or undefined when calling updateRatingSystemParameter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating-system/parameter/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingSystemParameterToJSON(requestParameters['ratingSystemParameter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingSystemParameterFromJSON(jsonValue));
    }

    /**
     * Update rating system parameter
     */
    async updateRatingSystemParameter(requestParameters: UpdateRatingSystemParameterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingSystemParameter> {
        const response = await this.updateRatingSystemParameterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
