/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PulsarrUserModel,
} from '../models/index';
import {
    PulsarrUserModelFromJSON,
    PulsarrUserModelToJSON,
} from '../models/index';

export interface AddUserRequest {
    pulsarrUserModel: PulsarrUserModel;
}

export interface DeleteUserRequest {
    id: number;
}

export interface GetPulsarrUserRequest {
    id: number;
}

export interface UpdateUserRequest {
    pulsarrUserModel: PulsarrUserModel;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Add user
     */
    async addUserRaw(requestParameters: AddUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PulsarrUserModel>> {
        if (requestParameters['pulsarrUserModel'] == null) {
            throw new runtime.RequiredError(
                'pulsarrUserModel',
                'Required parameter "pulsarrUserModel" was null or undefined when calling addUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PulsarrUserModelToJSON(requestParameters['pulsarrUserModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PulsarrUserModelFromJSON(jsonValue));
    }

    /**
     * Add user
     */
    async addUser(requestParameters: AddUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PulsarrUserModel> {
        const response = await this.addUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete user
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/user/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete user
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.deleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all users
     */
    async getAllUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PulsarrUserModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/user/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PulsarrUserModelFromJSON));
    }

    /**
     * Get all users
     */
    async getAllUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PulsarrUserModel>> {
        const response = await this.getAllUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a user by id
     */
    async getPulsarrUserRaw(requestParameters: GetPulsarrUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PulsarrUserModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPulsarrUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/user/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PulsarrUserModelFromJSON(jsonValue));
    }

    /**
     * Get a user by id
     */
    async getPulsarrUser(requestParameters: GetPulsarrUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PulsarrUserModel> {
        const response = await this.getPulsarrUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update user
     */
    async updateUserRaw(requestParameters: UpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PulsarrUserModel>> {
        if (requestParameters['pulsarrUserModel'] == null) {
            throw new runtime.RequiredError(
                'pulsarrUserModel',
                'Required parameter "pulsarrUserModel" was null or undefined when calling updateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PulsarrUserModelToJSON(requestParameters['pulsarrUserModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PulsarrUserModelFromJSON(jsonValue));
    }

    /**
     * Update user
     */
    async updateUser(requestParameters: UpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PulsarrUserModel> {
        const response = await this.updateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
