/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Artist } from './Artist';
import {
    ArtistFromJSON,
    ArtistFromJSONTyped,
    ArtistToJSON,
    ArtistToJSONTyped,
} from './Artist';

/**
 * 
 * @export
 * @interface ArtistCredit
 */
export interface ArtistCredit {
    /**
     * 
     * @type {string}
     * @memberof ArtistCredit
     */
    name?: string | null;
    /**
     * 
     * @type {Artist}
     * @memberof ArtistCredit
     */
    artist?: Artist | null;
}

/**
 * Check if a given object implements the ArtistCredit interface.
 */
export function instanceOfArtistCredit(value: object): value is ArtistCredit {
    return true;
}

export function ArtistCreditFromJSON(json: any): ArtistCredit {
    return ArtistCreditFromJSONTyped(json, false);
}

export function ArtistCreditFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistCredit {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'artist': json['artist'] == null ? undefined : ArtistFromJSON(json['artist']),
    };
}

export function ArtistCreditToJSON(json: any): ArtistCredit {
    return ArtistCreditToJSONTyped(json, false);
}

export function ArtistCreditToJSONTyped(value?: ArtistCredit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'artist': ArtistToJSON(value['artist']),
    };
}

