/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Artist } from './Artist';
import {
    ArtistFromJSON,
    ArtistFromJSONTyped,
    ArtistToJSON,
    ArtistToJSONTyped,
} from './Artist';

/**
 * 
 * @export
 * @interface ArtistSearchResponse
 */
export interface ArtistSearchResponse {
    /**
     * 
     * @type {string}
     * @memberof ArtistSearchResponse
     */
    created?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ArtistSearchResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ArtistSearchResponse
     */
    offset: number;
    /**
     * 
     * @type {Array<Artist>}
     * @memberof ArtistSearchResponse
     */
    artists: Array<Artist>;
}

/**
 * Check if a given object implements the ArtistSearchResponse interface.
 */
export function instanceOfArtistSearchResponse(value: object): value is ArtistSearchResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('artists' in value) || value['artists'] === undefined) return false;
    return true;
}

export function ArtistSearchResponseFromJSON(json: any): ArtistSearchResponse {
    return ArtistSearchResponseFromJSONTyped(json, false);
}

export function ArtistSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'count': json['count'],
        'offset': json['offset'],
        'artists': ((json['artists'] as Array<any>).map(ArtistFromJSON)),
    };
}

export function ArtistSearchResponseToJSON(json: any): ArtistSearchResponse {
    return ArtistSearchResponseToJSONTyped(json, false);
}

export function ArtistSearchResponseToJSONTyped(value?: ArtistSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'count': value['count'],
        'offset': value['offset'],
        'artists': ((value['artists'] as Array<any>).map(ArtistToJSON)),
    };
}

