/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Work } from './Work';
import {
    WorkFromJSON,
    WorkFromJSONTyped,
    WorkToJSON,
    WorkToJSONTyped,
} from './Work';
import type { LifeSpan } from './LifeSpan';
import {
    LifeSpanFromJSON,
    LifeSpanFromJSONTyped,
    LifeSpanToJSON,
    LifeSpanToJSONTyped,
} from './LifeSpan';
import type { Recording } from './Recording';
import {
    RecordingFromJSON,
    RecordingFromJSONTyped,
    RecordingToJSON,
    RecordingToJSONTyped,
} from './Recording';
import type { ReleaseGroup } from './ReleaseGroup';
import {
    ReleaseGroupFromJSON,
    ReleaseGroupFromJSONTyped,
    ReleaseGroupToJSON,
    ReleaseGroupToJSONTyped,
} from './ReleaseGroup';
import type { Release } from './Release';
import {
    ReleaseFromJSON,
    ReleaseFromJSONTyped,
    ReleaseToJSON,
    ReleaseToJSONTyped,
} from './Release';

/**
 * 
 * @export
 * @interface Artist
 */
export interface Artist {
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    sort_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    disambiguation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    country?: string | null;
    /**
     * 
     * @type {LifeSpan}
     * @memberof Artist
     */
    life_span?: LifeSpan | null;
    /**
     * 
     * @type {Array<Release>}
     * @memberof Artist
     */
    releases?: Array<Release> | null;
    /**
     * 
     * @type {Array<ReleaseGroup>}
     * @memberof Artist
     */
    release_groups?: Array<ReleaseGroup> | null;
    /**
     * 
     * @type {Array<Recording>}
     * @memberof Artist
     */
    recordings?: Array<Recording> | null;
    /**
     * 
     * @type {Array<Work>}
     * @memberof Artist
     */
    works?: Array<Work> | null;
}

/**
 * Check if a given object implements the Artist interface.
 */
export function instanceOfArtist(value: object): value is Artist {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ArtistFromJSON(json: any): Artist {
    return ArtistFromJSONTyped(json, false);
}

export function ArtistFromJSONTyped(json: any, ignoreDiscriminator: boolean): Artist {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sort_name': json['sort-name'] == null ? undefined : json['sort-name'],
        'type': json['type'] == null ? undefined : json['type'],
        'disambiguation': json['disambiguation'] == null ? undefined : json['disambiguation'],
        'country': json['country'] == null ? undefined : json['country'],
        'life_span': json['life-span'] == null ? undefined : LifeSpanFromJSON(json['life-span']),
        'releases': json['releases'] == null ? undefined : ((json['releases'] as Array<any>).map(ReleaseFromJSON)),
        'release_groups': json['release-groups'] == null ? undefined : ((json['release-groups'] as Array<any>).map(ReleaseGroupFromJSON)),
        'recordings': json['recordings'] == null ? undefined : ((json['recordings'] as Array<any>).map(RecordingFromJSON)),
        'works': json['works'] == null ? undefined : ((json['works'] as Array<any>).map(WorkFromJSON)),
    };
}

export function ArtistToJSON(json: any): Artist {
    return ArtistToJSONTyped(json, false);
}

export function ArtistToJSONTyped(value?: Artist | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'sort-name': value['sort_name'],
        'type': value['type'],
        'disambiguation': value['disambiguation'],
        'country': value['country'],
        'life-span': LifeSpanToJSON(value['life_span']),
        'releases': value['releases'] == null ? undefined : ((value['releases'] as Array<any>).map(ReleaseToJSON)),
        'release-groups': value['release_groups'] == null ? undefined : ((value['release_groups'] as Array<any>).map(ReleaseGroupToJSON)),
        'recordings': value['recordings'] == null ? undefined : ((value['recordings'] as Array<any>).map(RecordingToJSON)),
        'works': value['works'] == null ? undefined : ((value['works'] as Array<any>).map(WorkToJSON)),
    };
}

