/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistCount
 */
export interface ArtistCount {
    /**
     * 
     * @type {string}
     * @memberof ArtistCount
     */
    artist_name: string;
    /**
     * 
     * @type {number}
     * @memberof ArtistCount
     */
    count: number;
}

/**
 * Check if a given object implements the ArtistCount interface.
 */
export function instanceOfArtistCount(value: object): value is ArtistCount {
    if (!('artist_name' in value) || value['artist_name'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ArtistCountFromJSON(json: any): ArtistCount {
    return ArtistCountFromJSONTyped(json, false);
}

export function ArtistCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistCount {
    if (json == null) {
        return json;
    }
    return {
        
        'artist_name': json['artist_name'],
        'count': json['count'],
    };
}

export function ArtistCountToJSON(json: any): ArtistCount {
    return ArtistCountToJSONTyped(json, false);
}

export function ArtistCountToJSONTyped(value?: ArtistCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artist_name': value['artist_name'],
        'count': value['count'],
    };
}

