/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoverArtThumbnails
 */
export interface CoverArtThumbnails {
    /**
     * 
     * @type {string}
     * @memberof CoverArtThumbnails
     */
    _250?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoverArtThumbnails
     */
    _500?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoverArtThumbnails
     */
    _1200?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoverArtThumbnails
     */
    small?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoverArtThumbnails
     */
    large?: string | null;
}

/**
 * Check if a given object implements the CoverArtThumbnails interface.
 */
export function instanceOfCoverArtThumbnails(value: object): value is CoverArtThumbnails {
    return true;
}

export function CoverArtThumbnailsFromJSON(json: any): CoverArtThumbnails {
    return CoverArtThumbnailsFromJSONTyped(json, false);
}

export function CoverArtThumbnailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverArtThumbnails {
    if (json == null) {
        return json;
    }
    return {
        
        '_250': json['250'] == null ? undefined : json['250'],
        '_500': json['500'] == null ? undefined : json['500'],
        '_1200': json['1200'] == null ? undefined : json['1200'],
        'small': json['small'] == null ? undefined : json['small'],
        'large': json['large'] == null ? undefined : json['large'],
    };
}

export function CoverArtThumbnailsToJSON(json: any): CoverArtThumbnails {
    return CoverArtThumbnailsToJSONTyped(json, false);
}

export function CoverArtThumbnailsToJSONTyped(value?: CoverArtThumbnails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '250': value['_250'],
        '500': value['_500'],
        '1200': value['_1200'],
        'small': value['small'],
        'large': value['large'],
    };
}

