/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoverArtThumbnails } from './CoverArtThumbnails';
import {
    CoverArtThumbnailsFromJSON,
    CoverArtThumbnailsFromJSONTyped,
    CoverArtThumbnailsToJSON,
    CoverArtThumbnailsToJSONTyped,
} from './CoverArtThumbnails';

/**
 * 
 * @export
 * @interface CoverArtImage
 */
export interface CoverArtImage {
    /**
     * 
     * @type {number}
     * @memberof CoverArtImage
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CoverArtImage
     */
    image: string;
    /**
     * 
     * @type {CoverArtThumbnails}
     * @memberof CoverArtImage
     */
    thumbnails?: CoverArtThumbnails | null;
    /**
     * 
     * @type {boolean}
     * @memberof CoverArtImage
     */
    front: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CoverArtImage
     */
    back: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CoverArtImage
     */
    types: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CoverArtImage
     */
    comment?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CoverArtImage
     */
    approved?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof CoverArtImage
     */
    edit?: number | null;
}

/**
 * Check if a given object implements the CoverArtImage interface.
 */
export function instanceOfCoverArtImage(value: object): value is CoverArtImage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('front' in value) || value['front'] === undefined) return false;
    if (!('back' in value) || value['back'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    return true;
}

export function CoverArtImageFromJSON(json: any): CoverArtImage {
    return CoverArtImageFromJSONTyped(json, false);
}

export function CoverArtImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverArtImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': json['image'],
        'thumbnails': json['thumbnails'] == null ? undefined : CoverArtThumbnailsFromJSON(json['thumbnails']),
        'front': json['front'],
        'back': json['back'],
        'types': json['types'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'approved': json['approved'] == null ? undefined : json['approved'],
        'edit': json['edit'] == null ? undefined : json['edit'],
    };
}

export function CoverArtImageToJSON(json: any): CoverArtImage {
    return CoverArtImageToJSONTyped(json, false);
}

export function CoverArtImageToJSONTyped(value?: CoverArtImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'image': value['image'],
        'thumbnails': CoverArtThumbnailsToJSON(value['thumbnails']),
        'front': value['front'],
        'back': value['back'],
        'types': value['types'],
        'comment': value['comment'],
        'approved': value['approved'],
        'edit': value['edit'],
    };
}

