/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericResponse
 */
export interface GenericResponse {
    /**
     * 
     * @type {string}
     * @memberof GenericResponse
     */
    message: string;
}

/**
 * Check if a given object implements the GenericResponse interface.
 */
export function instanceOfGenericResponse(value: object): value is GenericResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GenericResponseFromJSON(json: any): GenericResponse {
    return GenericResponseFromJSONTyped(json, false);
}

export function GenericResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function GenericResponseToJSON(json: any): GenericResponse {
    return GenericResponseToJSONTyped(json, false);
}

export function GenericResponseToJSONTyped(value?: GenericResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

