/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRequest
 */
export interface GetRequest {
    /**
     * 
     * @type {number}
     * @memberof GetRequest
     */
    take_size?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetRequest
     */
    offset?: number | null;
}

/**
 * Check if a given object implements the GetRequest interface.
 */
export function instanceOfGetRequest(value: object): value is GetRequest {
    return true;
}

export function GetRequestFromJSON(json: any): GetRequest {
    return GetRequestFromJSONTyped(json, false);
}

export function GetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'take_size': json['take_size'] == null ? undefined : json['take_size'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function GetRequestToJSON(json: any): GetRequest {
    return GetRequestToJSONTyped(json, false);
}

export function GetRequestToJSONTyped(value?: GetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'take_size': value['take_size'],
        'offset': value['offset'],
    };
}

