/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface GroupMemberDTO
 */
export interface GroupMemberDTO {
    /**
     * 
     * @type {number}
     * @memberof GroupMemberDTO
     */
    pulsarr_group_id: number;
    /**
     * 
     * @type {UserDTO}
     * @memberof GroupMemberDTO
     */
    user: UserDTO;
    /**
     * 
     * @type {string}
     * @memberof GroupMemberDTO
     */
    group_role: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMemberDTO
     */
    join_date: string;
}

/**
 * Check if a given object implements the GroupMemberDTO interface.
 */
export function instanceOfGroupMemberDTO(value: object): value is GroupMemberDTO {
    if (!('pulsarr_group_id' in value) || value['pulsarr_group_id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('group_role' in value) || value['group_role'] === undefined) return false;
    if (!('join_date' in value) || value['join_date'] === undefined) return false;
    return true;
}

export function GroupMemberDTOFromJSON(json: any): GroupMemberDTO {
    return GroupMemberDTOFromJSONTyped(json, false);
}

export function GroupMemberDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMemberDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'pulsarr_group_id': json['pulsarr_group_id'],
        'user': UserDTOFromJSON(json['user']),
        'group_role': json['group_role'],
        'join_date': json['join_date'],
    };
}

export function GroupMemberDTOToJSON(json: any): GroupMemberDTO {
    return GroupMemberDTOToJSONTyped(json, false);
}

export function GroupMemberDTOToJSONTyped(value?: GroupMemberDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pulsarr_group_id': value['pulsarr_group_id'],
        'user': UserDTOToJSON(value['user']),
        'group_role': value['group_role'],
        'join_date': value['join_date'],
    };
}

