/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupAlbumKey
 */
export interface GroupAlbumKey {
    /**
     * 
     * @type {number}
     * @memberof GroupAlbumKey
     */
    group_id: number;
    /**
     * 
     * @type {string}
     * @memberof GroupAlbumKey
     */
    musicbrainz_id: string;
}

/**
 * Check if a given object implements the GroupAlbumKey interface.
 */
export function instanceOfGroupAlbumKey(value: object): value is GroupAlbumKey {
    if (!('group_id' in value) || value['group_id'] === undefined) return false;
    if (!('musicbrainz_id' in value) || value['musicbrainz_id'] === undefined) return false;
    return true;
}

export function GroupAlbumKeyFromJSON(json: any): GroupAlbumKey {
    return GroupAlbumKeyFromJSONTyped(json, false);
}

export function GroupAlbumKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupAlbumKey {
    if (json == null) {
        return json;
    }
    return {
        
        'group_id': json['group_id'],
        'musicbrainz_id': json['musicbrainz_id'],
    };
}

export function GroupAlbumKeyToJSON(json: any): GroupAlbumKey {
    return GroupAlbumKeyToJSONTyped(json, false);
}

export function GroupAlbumKeyToJSONTyped(value?: GroupAlbumKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['group_id'],
        'musicbrainz_id': value['musicbrainz_id'],
    };
}

