/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupAlbumKey } from './GroupAlbumKey';
import {
    GroupAlbumKeyFromJSON,
    GroupAlbumKeyFromJSONTyped,
    GroupAlbumKeyToJSON,
    GroupAlbumKeyToJSONTyped,
} from './GroupAlbumKey';

/**
 * 
 * @export
 * @interface GroupAveragesRequest
 */
export interface GroupAveragesRequest {
    /**
     * 
     * @type {Array<GroupAlbumKey>}
     * @memberof GroupAveragesRequest
     */
    items: Array<GroupAlbumKey>;
}

/**
 * Check if a given object implements the GroupAveragesRequest interface.
 */
export function instanceOfGroupAveragesRequest(value: object): value is GroupAveragesRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GroupAveragesRequestFromJSON(json: any): GroupAveragesRequest {
    return GroupAveragesRequestFromJSONTyped(json, false);
}

export function GroupAveragesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupAveragesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GroupAlbumKeyFromJSON)),
    };
}

export function GroupAveragesRequestToJSON(json: any): GroupAveragesRequest {
    return GroupAveragesRequestToJSONTyped(json, false);
}

export function GroupAveragesRequestToJSONTyped(value?: GroupAveragesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GroupAlbumKeyToJSON)),
    };
}

