/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupMemberDTO } from './GroupMemberDTO';
import {
    GroupMemberDTOFromJSON,
    GroupMemberDTOFromJSONTyped,
    GroupMemberDTOToJSON,
    GroupMemberDTOToJSONTyped,
} from './GroupMemberDTO';
import type { RatingSystemDTO } from './RatingSystemDTO';
import {
    RatingSystemDTOFromJSON,
    RatingSystemDTOFromJSONTyped,
    RatingSystemDTOToJSON,
    RatingSystemDTOToJSONTyped,
} from './RatingSystemDTO';

/**
 * 
 * @export
 * @interface GroupDTO
 */
export interface GroupDTO {
    /**
     * 
     * @type {number}
     * @memberof GroupDTO
     */
    pulsarr_group_id: number;
    /**
     * 
     * @type {number}
     * @memberof GroupDTO
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    privacy_type: string;
    /**
     * 
     * @type {RatingSystemDTO}
     * @memberof GroupDTO
     */
    rating_system?: RatingSystemDTO | null;
    /**
     * 
     * @type {number}
     * @memberof GroupDTO
     */
    created_by_user_id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    creation_date?: string | null;
    /**
     * 
     * @type {Array<GroupMemberDTO>}
     * @memberof GroupDTO
     */
    members?: Array<GroupMemberDTO> | null;
}

/**
 * Check if a given object implements the GroupDTO interface.
 */
export function instanceOfGroupDTO(value: object): value is GroupDTO {
    if (!('pulsarr_group_id' in value) || value['pulsarr_group_id'] === undefined) return false;
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('privacy_type' in value) || value['privacy_type'] === undefined) return false;
    return true;
}

export function GroupDTOFromJSON(json: any): GroupDTO {
    return GroupDTOFromJSONTyped(json, false);
}

export function GroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'pulsarr_group_id': json['pulsarr_group_id'],
        'rating_system_id': json['rating_system_id'],
        'name': json['name'],
        'privacy_type': json['privacy_type'],
        'rating_system': json['rating_system'] == null ? undefined : RatingSystemDTOFromJSON(json['rating_system']),
        'created_by_user_id': json['created_by_user_id'] == null ? undefined : json['created_by_user_id'],
        'creation_date': json['creation_date'] == null ? undefined : json['creation_date'],
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(GroupMemberDTOFromJSON)),
    };
}

export function GroupDTOToJSON(json: any): GroupDTO {
    return GroupDTOToJSONTyped(json, false);
}

export function GroupDTOToJSONTyped(value?: GroupDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pulsarr_group_id': value['pulsarr_group_id'],
        'rating_system_id': value['rating_system_id'],
        'name': value['name'],
        'privacy_type': value['privacy_type'],
        'rating_system': RatingSystemDTOToJSON(value['rating_system']),
        'created_by_user_id': value['created_by_user_id'],
        'creation_date': value['creation_date'],
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(GroupMemberDTOToJSON)),
    };
}

