/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Label } from './Label';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label';

/**
 * 
 * @export
 * @interface LabelInfo
 */
export interface LabelInfo {
    /**
     * 
     * @type {string}
     * @memberof LabelInfo
     */
    catalog_number?: string | null;
    /**
     * 
     * @type {Label}
     * @memberof LabelInfo
     */
    label?: Label | null;
}

/**
 * Check if a given object implements the LabelInfo interface.
 */
export function instanceOfLabelInfo(value: object): value is LabelInfo {
    return true;
}

export function LabelInfoFromJSON(json: any): LabelInfo {
    return LabelInfoFromJSONTyped(json, false);
}

export function LabelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'catalog_number': json['catalog-number'] == null ? undefined : json['catalog-number'],
        'label': json['label'] == null ? undefined : LabelFromJSON(json['label']),
    };
}

export function LabelInfoToJSON(json: any): LabelInfo {
    return LabelInfoToJSONTyped(json, false);
}

export function LabelInfoToJSONTyped(value?: LabelInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catalog-number': value['catalog_number'],
        'label': LabelToJSON(value['label']),
    };
}

