/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LifeSpan } from './LifeSpan';
import {
    LifeSpanFromJSON,
    LifeSpanFromJSONTyped,
    LifeSpanToJSON,
    LifeSpanToJSONTyped,
} from './LifeSpan';

/**
 * 
 * @export
 * @interface Label
 */
export interface Label {
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    sort_name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Label
     */
    label_code?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    disambiguation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    country?: string | null;
    /**
     * 
     * @type {LifeSpan}
     * @memberof Label
     */
    life_span?: LifeSpan | null;
}

/**
 * Check if a given object implements the Label interface.
 */
export function instanceOfLabel(value: object): value is Label {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function LabelFromJSON(json: any): Label {
    return LabelFromJSONTyped(json, false);
}

export function LabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Label {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sort_name': json['sort-name'] == null ? undefined : json['sort-name'],
        'label_code': json['label-code'] == null ? undefined : json['label-code'],
        'type': json['type'] == null ? undefined : json['type'],
        'disambiguation': json['disambiguation'] == null ? undefined : json['disambiguation'],
        'country': json['country'] == null ? undefined : json['country'],
        'life_span': json['life-span'] == null ? undefined : LifeSpanFromJSON(json['life-span']),
    };
}

export function LabelToJSON(json: any): Label {
    return LabelToJSONTyped(json, false);
}

export function LabelToJSONTyped(value?: Label | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'sort-name': value['sort_name'],
        'label-code': value['label_code'],
        'type': value['type'],
        'disambiguation': value['disambiguation'],
        'country': value['country'],
        'life-span': LifeSpanToJSON(value['life_span']),
    };
}

