/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LifeSpan
 */
export interface LifeSpan {
    /**
     * 
     * @type {string}
     * @memberof LifeSpan
     */
    begin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LifeSpan
     */
    end?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LifeSpan
     */
    ended?: boolean | null;
}

/**
 * Check if a given object implements the LifeSpan interface.
 */
export function instanceOfLifeSpan(value: object): value is LifeSpan {
    return true;
}

export function LifeSpanFromJSON(json: any): LifeSpan {
    return LifeSpanFromJSONTyped(json, false);
}

export function LifeSpanFromJSONTyped(json: any, ignoreDiscriminator: boolean): LifeSpan {
    if (json == null) {
        return json;
    }
    return {
        
        'begin': json['begin'] == null ? undefined : json['begin'],
        'end': json['end'] == null ? undefined : json['end'],
        'ended': json['ended'] == null ? undefined : json['ended'],
    };
}

export function LifeSpanToJSON(json: any): LifeSpan {
    return LifeSpanToJSONTyped(json, false);
}

export function LifeSpanToJSONTyped(value?: LifeSpan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'begin': value['begin'],
        'end': value['end'],
        'ended': value['ended'],
    };
}

