/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginatedGroupRatingsRequest
 */
export interface PaginatedGroupRatingsRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof PaginatedGroupRatingsRequest
     */
    group_ids: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedGroupRatingsRequest
     */
    take_size?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginatedGroupRatingsRequest
     */
    offset?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedGroupRatingsRequest
     */
    current_only?: boolean | null;
}

/**
 * Check if a given object implements the PaginatedGroupRatingsRequest interface.
 */
export function instanceOfPaginatedGroupRatingsRequest(value: object): value is PaginatedGroupRatingsRequest {
    if (!('group_ids' in value) || value['group_ids'] === undefined) return false;
    return true;
}

export function PaginatedGroupRatingsRequestFromJSON(json: any): PaginatedGroupRatingsRequest {
    return PaginatedGroupRatingsRequestFromJSONTyped(json, false);
}

export function PaginatedGroupRatingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGroupRatingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'group_ids': json['group_ids'],
        'take_size': json['take_size'] == null ? undefined : json['take_size'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'current_only': json['current_only'] == null ? undefined : json['current_only'],
    };
}

export function PaginatedGroupRatingsRequestToJSON(json: any): PaginatedGroupRatingsRequest {
    return PaginatedGroupRatingsRequestToJSONTyped(json, false);
}

export function PaginatedGroupRatingsRequestToJSONTyped(value?: PaginatedGroupRatingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_ids': value['group_ids'],
        'take_size': value['take_size'],
        'offset': value['offset'],
        'current_only': value['current_only'],
    };
}

