/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PulsarrGroup
 */
export interface PulsarrGroup {
    /**
     * 
     * @type {number}
     * @memberof PulsarrGroup
     */
    pulsarr_group_id: number;
    /**
     * 
     * @type {number}
     * @memberof PulsarrGroup
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof PulsarrGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PulsarrGroup
     */
    privacy_type: string;
}

/**
 * Check if a given object implements the PulsarrGroup interface.
 */
export function instanceOfPulsarrGroup(value: object): value is PulsarrGroup {
    if (!('pulsarr_group_id' in value) || value['pulsarr_group_id'] === undefined) return false;
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('privacy_type' in value) || value['privacy_type'] === undefined) return false;
    return true;
}

export function PulsarrGroupFromJSON(json: any): PulsarrGroup {
    return PulsarrGroupFromJSONTyped(json, false);
}

export function PulsarrGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): PulsarrGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'pulsarr_group_id': json['pulsarr_group_id'],
        'rating_system_id': json['rating_system_id'],
        'name': json['name'],
        'privacy_type': json['privacy_type'],
    };
}

export function PulsarrGroupToJSON(json: any): PulsarrGroup {
    return PulsarrGroupToJSONTyped(json, false);
}

export function PulsarrGroupToJSONTyped(value?: PulsarrGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pulsarr_group_id': value['pulsarr_group_id'],
        'rating_system_id': value['rating_system_id'],
        'name': value['name'],
        'privacy_type': value['privacy_type'],
    };
}

