/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PulsarrUserModel
 */
export interface PulsarrUserModel {
    /**
     * 
     * @type {number}
     * @memberof PulsarrUserModel
     */
    pulsarrUserId: number;
    /**
     * 
     * @type {string}
     * @memberof PulsarrUserModel
     */
    name: string;
}

/**
 * Check if a given object implements the PulsarrUserModel interface.
 */
export function instanceOfPulsarrUserModel(value: object): value is PulsarrUserModel {
    if (!('pulsarrUserId' in value) || value['pulsarrUserId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PulsarrUserModelFromJSON(json: any): PulsarrUserModel {
    return PulsarrUserModelFromJSONTyped(json, false);
}

export function PulsarrUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PulsarrUserModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pulsarrUserId': json['pulsarr_user_id'],
        'name': json['name'],
    };
}

export function PulsarrUserModelToJSON(json: any): PulsarrUserModel {
    return PulsarrUserModelToJSONTyped(json, false);
}

export function PulsarrUserModelToJSONTyped(value?: PulsarrUserModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pulsarr_user_id': value['pulsarrUserId'],
        'name': value['name'],
    };
}

