/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PulsarrGroupModel
 */
export interface PulsarrGroupModel {
    /**
     * 
     * @type {number}
     * @memberof PulsarrGroupModel
     */
    pulsarrGroupId: number;
    /**
     * 
     * @type {number}
     * @memberof PulsarrGroupModel
     */
    ratingSystemId: number;
    /**
     * 
     * @type {string}
     * @memberof PulsarrGroupModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PulsarrGroupModel
     */
    privacyType: string;
}

/**
 * Check if a given object implements the PulsarrGroupModel interface.
 */
export function instanceOfPulsarrGroupModel(value: object): value is PulsarrGroupModel {
    if (!('pulsarrGroupId' in value) || value['pulsarrGroupId'] === undefined) return false;
    if (!('ratingSystemId' in value) || value['ratingSystemId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('privacyType' in value) || value['privacyType'] === undefined) return false;
    return true;
}

export function PulsarrGroupModelFromJSON(json: any): PulsarrGroupModel {
    return PulsarrGroupModelFromJSONTyped(json, false);
}

export function PulsarrGroupModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PulsarrGroupModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pulsarrGroupId': json['pulsarr_group_id'],
        'ratingSystemId': json['rating_system_id'],
        'name': json['name'],
        'privacyType': json['privacy_type'],
    };
}

export function PulsarrGroupModelToJSON(json: any): PulsarrGroupModel {
    return PulsarrGroupModelToJSONTyped(json, false);
}

export function PulsarrGroupModelToJSONTyped(value?: PulsarrGroupModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pulsarr_group_id': value['pulsarrGroupId'],
        'rating_system_id': value['ratingSystemId'],
        'name': value['name'],
        'privacy_type': value['privacyType'],
    };
}

