/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatingSystemTemplateParameterDTO } from './RatingSystemTemplateParameterDTO';
import {
    RatingSystemTemplateParameterDTOFromJSON,
    RatingSystemTemplateParameterDTOFromJSONTyped,
    RatingSystemTemplateParameterDTOToJSON,
    RatingSystemTemplateParameterDTOToJSONTyped,
} from './RatingSystemTemplateParameterDTO';

/**
 * 
 * @export
 * @interface RatingSystemTemplateDTO
 */
export interface RatingSystemTemplateDTO {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemTemplateDTO
     */
    template_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplateDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplateDTO
     */
    master_rating_type: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplateDTO
     */
    rating_max: string;
    /**
     * 
     * @type {Array<RatingSystemTemplateParameterDTO>}
     * @memberof RatingSystemTemplateDTO
     */
    parameters?: Array<RatingSystemTemplateParameterDTO> | null;
}

/**
 * Check if a given object implements the RatingSystemTemplateDTO interface.
 */
export function instanceOfRatingSystemTemplateDTO(value: object): value is RatingSystemTemplateDTO {
    if (!('template_id' in value) || value['template_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('master_rating_type' in value) || value['master_rating_type'] === undefined) return false;
    if (!('rating_max' in value) || value['rating_max'] === undefined) return false;
    return true;
}

export function RatingSystemTemplateDTOFromJSON(json: any): RatingSystemTemplateDTO {
    return RatingSystemTemplateDTOFromJSONTyped(json, false);
}

export function RatingSystemTemplateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemTemplateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'template_id': json['template_id'],
        'name': json['name'],
        'master_rating_type': json['master_rating_type'],
        'rating_max': json['rating_max'],
        'parameters': json['parameters'] == null ? undefined : ((json['parameters'] as Array<any>).map(RatingSystemTemplateParameterDTOFromJSON)),
    };
}

export function RatingSystemTemplateDTOToJSON(json: any): RatingSystemTemplateDTO {
    return RatingSystemTemplateDTOToJSONTyped(json, false);
}

export function RatingSystemTemplateDTOToJSONTyped(value?: RatingSystemTemplateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_id': value['template_id'],
        'name': value['name'],
        'master_rating_type': value['master_rating_type'],
        'rating_max': value['rating_max'],
        'parameters': value['parameters'] == null ? undefined : ((value['parameters'] as Array<any>).map(RatingSystemTemplateParameterDTOToJSON)),
    };
}

