/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystemTemplateParameterDTO
 */
export interface RatingSystemTemplateParameterDTO {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemTemplateParameterDTO
     */
    template_parameter_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingSystemTemplateParameterDTO
     */
    template_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplateParameterDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplateParameterDTO
     */
    parameter_rating_max: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplateParameterDTO
     */
    weight: string;
}

/**
 * Check if a given object implements the RatingSystemTemplateParameterDTO interface.
 */
export function instanceOfRatingSystemTemplateParameterDTO(value: object): value is RatingSystemTemplateParameterDTO {
    if (!('template_parameter_id' in value) || value['template_parameter_id'] === undefined) return false;
    if (!('template_id' in value) || value['template_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('parameter_rating_max' in value) || value['parameter_rating_max'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function RatingSystemTemplateParameterDTOFromJSON(json: any): RatingSystemTemplateParameterDTO {
    return RatingSystemTemplateParameterDTOFromJSONTyped(json, false);
}

export function RatingSystemTemplateParameterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemTemplateParameterDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'template_parameter_id': json['template_parameter_id'],
        'template_id': json['template_id'],
        'name': json['name'],
        'parameter_rating_max': json['parameter_rating_max'],
        'weight': json['weight'],
    };
}

export function RatingSystemTemplateParameterDTOToJSON(json: any): RatingSystemTemplateParameterDTO {
    return RatingSystemTemplateParameterDTOToJSONTyped(json, false);
}

export function RatingSystemTemplateParameterDTOToJSONTyped(value?: RatingSystemTemplateParameterDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_parameter_id': value['template_parameter_id'],
        'template_id': value['template_id'],
        'name': value['name'],
        'parameter_rating_max': value['parameter_rating_max'],
        'weight': value['weight'],
    };
}

