/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingModel
 */
export interface RatingModel {
    /**
     * 
     * @type {number}
     * @memberof RatingModel
     */
    ratingId: number;
    /**
     * 
     * @type {number}
     * @memberof RatingModel
     */
    pulsarrUserId: number;
    /**
     * 
     * @type {number}
     * @memberof RatingModel
     */
    pulsarrGroupId: number;
    /**
     * 
     * @type {number}
     * @memberof RatingModel
     */
    ratingSystemId: number;
    /**
     * 
     * @type {string}
     * @memberof RatingModel
     */
    comments: string;
    /**
     * 
     * @type {string}
     * @memberof RatingModel
     */
    ratingValue: string;
}

/**
 * Check if a given object implements the RatingModel interface.
 */
export function instanceOfRatingModel(value: object): value is RatingModel {
    if (!('ratingId' in value) || value['ratingId'] === undefined) return false;
    if (!('pulsarrUserId' in value) || value['pulsarrUserId'] === undefined) return false;
    if (!('pulsarrGroupId' in value) || value['pulsarrGroupId'] === undefined) return false;
    if (!('ratingSystemId' in value) || value['ratingSystemId'] === undefined) return false;
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('ratingValue' in value) || value['ratingValue'] === undefined) return false;
    return true;
}

export function RatingModelFromJSON(json: any): RatingModel {
    return RatingModelFromJSONTyped(json, false);
}

export function RatingModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ratingId': json['rating_id'],
        'pulsarrUserId': json['pulsarr_user_id'],
        'pulsarrGroupId': json['pulsarr_group_id'],
        'ratingSystemId': json['rating_system_id'],
        'comments': json['comments'],
        'ratingValue': json['rating_value'],
    };
}

export function RatingModelToJSON(json: any): RatingModel {
    return RatingModelToJSONTyped(json, false);
}

export function RatingModelToJSONTyped(value?: RatingModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_id': value['ratingId'],
        'pulsarr_user_id': value['pulsarrUserId'],
        'pulsarr_group_id': value['pulsarrGroupId'],
        'rating_system_id': value['ratingSystemId'],
        'comments': value['comments'],
        'rating_value': value['ratingValue'],
    };
}

