/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingDetailResponse
 */
export interface RatingDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof RatingDetailResponse
     */
    rating_detail_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetailResponse
     */
    rating_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetailResponse
     */
    rating_system_parameter_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingDetailResponse
     */
    rating_value: string;
    /**
     * 
     * @type {string}
     * @memberof RatingDetailResponse
     */
    parameter_name: string;
}

/**
 * Check if a given object implements the RatingDetailResponse interface.
 */
export function instanceOfRatingDetailResponse(value: object): value is RatingDetailResponse {
    if (!('rating_detail_id' in value) || value['rating_detail_id'] === undefined) return false;
    if (!('rating_id' in value) || value['rating_id'] === undefined) return false;
    if (!('rating_system_parameter_id' in value) || value['rating_system_parameter_id'] === undefined) return false;
    if (!('rating_value' in value) || value['rating_value'] === undefined) return false;
    if (!('parameter_name' in value) || value['parameter_name'] === undefined) return false;
    return true;
}

export function RatingDetailResponseFromJSON(json: any): RatingDetailResponse {
    return RatingDetailResponseFromJSONTyped(json, false);
}

export function RatingDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_detail_id': json['rating_detail_id'],
        'rating_id': json['rating_id'],
        'rating_system_parameter_id': json['rating_system_parameter_id'],
        'rating_value': json['rating_value'],
        'parameter_name': json['parameter_name'],
    };
}

export function RatingDetailResponseToJSON(json: any): RatingDetailResponse {
    return RatingDetailResponseToJSONTyped(json, false);
}

export function RatingDetailResponseToJSONTyped(value?: RatingDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_detail_id': value['rating_detail_id'],
        'rating_id': value['rating_id'],
        'rating_system_parameter_id': value['rating_system_parameter_id'],
        'rating_value': value['rating_value'],
        'parameter_name': value['parameter_name'],
    };
}

