/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatingSystemParameterDTO } from './RatingSystemParameterDTO';
import {
    RatingSystemParameterDTOFromJSON,
    RatingSystemParameterDTOFromJSONTyped,
    RatingSystemParameterDTOToJSON,
    RatingSystemParameterDTOToJSONTyped,
} from './RatingSystemParameterDTO';

/**
 * 
 * @export
 * @interface RatingSystemDTO
 */
export interface RatingSystemDTO {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemDTO
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemDTO
     */
    master_rating_type: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemDTO
     */
    rating_max: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemDTO
     */
    name: string;
    /**
     * 
     * @type {Array<RatingSystemParameterDTO>}
     * @memberof RatingSystemDTO
     */
    parameters: Array<RatingSystemParameterDTO>;
}

/**
 * Check if a given object implements the RatingSystemDTO interface.
 */
export function instanceOfRatingSystemDTO(value: object): value is RatingSystemDTO {
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('master_rating_type' in value) || value['master_rating_type'] === undefined) return false;
    if (!('rating_max' in value) || value['rating_max'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    return true;
}

export function RatingSystemDTOFromJSON(json: any): RatingSystemDTO {
    return RatingSystemDTOFromJSONTyped(json, false);
}

export function RatingSystemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_system_id': json['rating_system_id'],
        'master_rating_type': json['master_rating_type'],
        'rating_max': json['rating_max'],
        'name': json['name'],
        'parameters': ((json['parameters'] as Array<any>).map(RatingSystemParameterDTOFromJSON)),
    };
}

export function RatingSystemDTOToJSON(json: any): RatingSystemDTO {
    return RatingSystemDTOToJSONTyped(json, false);
}

export function RatingSystemDTOToJSONTyped(value?: RatingSystemDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_system_id': value['rating_system_id'],
        'master_rating_type': value['master_rating_type'],
        'rating_max': value['rating_max'],
        'name': value['name'],
        'parameters': ((value['parameters'] as Array<any>).map(RatingSystemParameterDTOToJSON)),
    };
}

