/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Rating
 */
export interface Rating {
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    rating_id: number;
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    pulsarr_user_id: number;
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    pulsarr_group_id: number;
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    comments: string;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    rating_value: string;
}

/**
 * Check if a given object implements the Rating interface.
 */
export function instanceOfRating(value: object): value is Rating {
    if (!('rating_id' in value) || value['rating_id'] === undefined) return false;
    if (!('pulsarr_user_id' in value) || value['pulsarr_user_id'] === undefined) return false;
    if (!('pulsarr_group_id' in value) || value['pulsarr_group_id'] === undefined) return false;
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('rating_value' in value) || value['rating_value'] === undefined) return false;
    return true;
}

export function RatingFromJSON(json: any): Rating {
    return RatingFromJSONTyped(json, false);
}

export function RatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rating {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_id': json['rating_id'],
        'pulsarr_user_id': json['pulsarr_user_id'],
        'pulsarr_group_id': json['pulsarr_group_id'],
        'rating_system_id': json['rating_system_id'],
        'comments': json['comments'],
        'rating_value': json['rating_value'],
    };
}

export function RatingToJSON(json: any): Rating {
    return RatingToJSONTyped(json, false);
}

export function RatingToJSONTyped(value?: Rating | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_id': value['rating_id'],
        'pulsarr_user_id': value['pulsarr_user_id'],
        'pulsarr_group_id': value['pulsarr_group_id'],
        'rating_system_id': value['rating_system_id'],
        'comments': value['comments'],
        'rating_value': value['rating_value'],
    };
}

