/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingDetailModel
 */
export interface RatingDetailModel {
    /**
     * 
     * @type {number}
     * @memberof RatingDetailModel
     */
    ratingDetailId: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetailModel
     */
    ratingId: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetailModel
     */
    ratingSystemParameterId: number;
    /**
     * 
     * @type {string}
     * @memberof RatingDetailModel
     */
    ratingValue: string;
}

/**
 * Check if a given object implements the RatingDetailModel interface.
 */
export function instanceOfRatingDetailModel(value: object): value is RatingDetailModel {
    if (!('ratingDetailId' in value) || value['ratingDetailId'] === undefined) return false;
    if (!('ratingId' in value) || value['ratingId'] === undefined) return false;
    if (!('ratingSystemParameterId' in value) || value['ratingSystemParameterId'] === undefined) return false;
    if (!('ratingValue' in value) || value['ratingValue'] === undefined) return false;
    return true;
}

export function RatingDetailModelFromJSON(json: any): RatingDetailModel {
    return RatingDetailModelFromJSONTyped(json, false);
}

export function RatingDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ratingDetailId': json['rating_detail_id'],
        'ratingId': json['rating_id'],
        'ratingSystemParameterId': json['rating_system_parameter_id'],
        'ratingValue': json['rating_value'],
    };
}

export function RatingDetailModelToJSON(json: any): RatingDetailModel {
    return RatingDetailModelToJSONTyped(json, false);
}

export function RatingDetailModelToJSONTyped(value?: RatingDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_detail_id': value['ratingDetailId'],
        'rating_id': value['ratingId'],
        'rating_system_parameter_id': value['ratingSystemParameterId'],
        'rating_value': value['ratingValue'],
    };
}

