/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystem
 */
export interface RatingSystem {
    /**
     * 
     * @type {number}
     * @memberof RatingSystem
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystem
     */
    master_rating_type: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystem
     */
    rating_max: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof RatingSystem
     */
    template_id?: number | null;
}

/**
 * Check if a given object implements the RatingSystem interface.
 */
export function instanceOfRatingSystem(value: object): value is RatingSystem {
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('master_rating_type' in value) || value['master_rating_type'] === undefined) return false;
    if (!('rating_max' in value) || value['rating_max'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RatingSystemFromJSON(json: any): RatingSystem {
    return RatingSystemFromJSONTyped(json, false);
}

export function RatingSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_system_id': json['rating_system_id'],
        'master_rating_type': json['master_rating_type'],
        'rating_max': json['rating_max'],
        'name': json['name'],
        'template_id': json['template_id'] == null ? undefined : json['template_id'],
    };
}

export function RatingSystemToJSON(json: any): RatingSystem {
    return RatingSystemToJSONTyped(json, false);
}

export function RatingSystemToJSONTyped(value?: RatingSystem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_system_id': value['rating_system_id'],
        'master_rating_type': value['master_rating_type'],
        'rating_max': value['rating_max'],
        'name': value['name'],
        'template_id': value['template_id'],
    };
}

