/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystemParameterDTO
 */
export interface RatingSystemParameterDTO {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemParameterDTO
     */
    rating_system_parameter_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingSystemParameterDTO
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemParameterDTO
     */
    parameter_rating_max: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemParameterDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemParameterDTO
     */
    weight: string;
}

/**
 * Check if a given object implements the RatingSystemParameterDTO interface.
 */
export function instanceOfRatingSystemParameterDTO(value: object): value is RatingSystemParameterDTO {
    if (!('rating_system_parameter_id' in value) || value['rating_system_parameter_id'] === undefined) return false;
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('parameter_rating_max' in value) || value['parameter_rating_max'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function RatingSystemParameterDTOFromJSON(json: any): RatingSystemParameterDTO {
    return RatingSystemParameterDTOFromJSONTyped(json, false);
}

export function RatingSystemParameterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemParameterDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_system_parameter_id': json['rating_system_parameter_id'],
        'rating_system_id': json['rating_system_id'],
        'parameter_rating_max': json['parameter_rating_max'],
        'name': json['name'],
        'weight': json['weight'],
    };
}

export function RatingSystemParameterDTOToJSON(json: any): RatingSystemParameterDTO {
    return RatingSystemParameterDTOToJSONTyped(json, false);
}

export function RatingSystemParameterDTOToJSONTyped(value?: RatingSystemParameterDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_system_parameter_id': value['rating_system_parameter_id'],
        'rating_system_id': value['rating_system_id'],
        'parameter_rating_max': value['parameter_rating_max'],
        'name': value['name'],
        'weight': value['weight'],
    };
}

