/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystemModel
 */
export interface RatingSystemModel {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemModel
     */
    ratingSystemId: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemModel
     */
    masterRatingType: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemModel
     */
    ratingMax: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemModel
     */
    name: string;
}

/**
 * Check if a given object implements the RatingSystemModel interface.
 */
export function instanceOfRatingSystemModel(value: object): value is RatingSystemModel {
    if (!('ratingSystemId' in value) || value['ratingSystemId'] === undefined) return false;
    if (!('masterRatingType' in value) || value['masterRatingType'] === undefined) return false;
    if (!('ratingMax' in value) || value['ratingMax'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RatingSystemModelFromJSON(json: any): RatingSystemModel {
    return RatingSystemModelFromJSONTyped(json, false);
}

export function RatingSystemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ratingSystemId': json['rating_system_id'],
        'masterRatingType': json['master_rating_type'],
        'ratingMax': json['rating_max'],
        'name': json['name'],
    };
}

export function RatingSystemModelToJSON(json: any): RatingSystemModel {
    return RatingSystemModelToJSONTyped(json, false);
}

export function RatingSystemModelToJSONTyped(value?: RatingSystemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_system_id': value['ratingSystemId'],
        'master_rating_type': value['masterRatingType'],
        'rating_max': value['ratingMax'],
        'name': value['name'],
    };
}

