/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystemTemplate
 */
export interface RatingSystemTemplate {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemTemplate
     */
    template_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplate
     */
    master_rating_type: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemTemplate
     */
    rating_max: string;
}

/**
 * Check if a given object implements the RatingSystemTemplate interface.
 */
export function instanceOfRatingSystemTemplate(value: object): value is RatingSystemTemplate {
    if (!('template_id' in value) || value['template_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('master_rating_type' in value) || value['master_rating_type'] === undefined) return false;
    if (!('rating_max' in value) || value['rating_max'] === undefined) return false;
    return true;
}

export function RatingSystemTemplateFromJSON(json: any): RatingSystemTemplate {
    return RatingSystemTemplateFromJSONTyped(json, false);
}

export function RatingSystemTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'template_id': json['template_id'],
        'name': json['name'],
        'master_rating_type': json['master_rating_type'],
        'rating_max': json['rating_max'],
    };
}

export function RatingSystemTemplateToJSON(json: any): RatingSystemTemplate {
    return RatingSystemTemplateToJSONTyped(json, false);
}

export function RatingSystemTemplateToJSONTyped(value?: RatingSystemTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_id': value['template_id'],
        'name': value['name'],
        'master_rating_type': value['master_rating_type'],
        'rating_max': value['rating_max'],
    };
}

