/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingDetailModel
 */
export interface RatingDetailModel {
    /**
     * 
     * @type {number}
     * @memberof RatingDetailModel
     */
    rating_detail_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetailModel
     */
    rating_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetailModel
     */
    rating_system_parameter_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingDetailModel
     */
    rating_value: string;
}

/**
 * Check if a given object implements the RatingDetailModel interface.
 */
export function instanceOfRatingDetailModel(value: object): value is RatingDetailModel {
    if (!('rating_detail_id' in value) || value['rating_detail_id'] === undefined) return false;
    if (!('rating_id' in value) || value['rating_id'] === undefined) return false;
    if (!('rating_system_parameter_id' in value) || value['rating_system_parameter_id'] === undefined) return false;
    if (!('rating_value' in value) || value['rating_value'] === undefined) return false;
    return true;
}

export function RatingDetailModelFromJSON(json: any): RatingDetailModel {
    return RatingDetailModelFromJSONTyped(json, false);
}

export function RatingDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_detail_id': json['rating_detail_id'],
        'rating_id': json['rating_id'],
        'rating_system_parameter_id': json['rating_system_parameter_id'],
        'rating_value': json['rating_value'],
    };
}

export function RatingDetailModelToJSON(json: any): RatingDetailModel {
    return RatingDetailModelToJSONTyped(json, false);
}

export function RatingDetailModelToJSONTyped(value?: RatingDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_detail_id': value['rating_detail_id'],
        'rating_id': value['rating_id'],
        'rating_system_parameter_id': value['rating_system_parameter_id'],
        'rating_value': value['rating_value'],
    };
}

