/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingDetail
 */
export interface RatingDetail {
    /**
     * 
     * @type {number}
     * @memberof RatingDetail
     */
    rating_detail_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetail
     */
    rating_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingDetail
     */
    rating_system_parameter_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingDetail
     */
    rating_value: string;
}

/**
 * Check if a given object implements the RatingDetail interface.
 */
export function instanceOfRatingDetail(value: object): value is RatingDetail {
    if (!('rating_detail_id' in value) || value['rating_detail_id'] === undefined) return false;
    if (!('rating_id' in value) || value['rating_id'] === undefined) return false;
    if (!('rating_system_parameter_id' in value) || value['rating_system_parameter_id'] === undefined) return false;
    if (!('rating_value' in value) || value['rating_value'] === undefined) return false;
    return true;
}

export function RatingDetailFromJSON(json: any): RatingDetail {
    return RatingDetailFromJSONTyped(json, false);
}

export function RatingDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_detail_id': json['rating_detail_id'],
        'rating_id': json['rating_id'],
        'rating_system_parameter_id': json['rating_system_parameter_id'],
        'rating_value': json['rating_value'],
    };
}

export function RatingDetailToJSON(json: any): RatingDetail {
    return RatingDetailToJSONTyped(json, false);
}

export function RatingDetailToJSONTyped(value?: RatingDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_detail_id': value['rating_detail_id'],
        'rating_id': value['rating_id'],
        'rating_system_parameter_id': value['rating_system_parameter_id'],
        'rating_value': value['rating_value'],
    };
}

