/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystemParameterModel
 */
export interface RatingSystemParameterModel {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemParameterModel
     */
    rating_system_parameter_id: number;
    /**
     * 
     * @type {number}
     * @memberof RatingSystemParameterModel
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemParameterModel
     */
    parameter_rating_max: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemParameterModel
     */
    name: string;
}

/**
 * Check if a given object implements the RatingSystemParameterModel interface.
 */
export function instanceOfRatingSystemParameterModel(value: object): value is RatingSystemParameterModel {
    if (!('rating_system_parameter_id' in value) || value['rating_system_parameter_id'] === undefined) return false;
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('parameter_rating_max' in value) || value['parameter_rating_max'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RatingSystemParameterModelFromJSON(json: any): RatingSystemParameterModel {
    return RatingSystemParameterModelFromJSONTyped(json, false);
}

export function RatingSystemParameterModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemParameterModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_system_parameter_id': json['rating_system_parameter_id'],
        'rating_system_id': json['rating_system_id'],
        'parameter_rating_max': json['parameter_rating_max'],
        'name': json['name'],
    };
}

export function RatingSystemParameterModelToJSON(json: any): RatingSystemParameterModel {
    return RatingSystemParameterModelToJSONTyped(json, false);
}

export function RatingSystemParameterModelToJSONTyped(value?: RatingSystemParameterModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_system_parameter_id': value['rating_system_parameter_id'],
        'rating_system_id': value['rating_system_id'],
        'parameter_rating_max': value['parameter_rating_max'],
        'name': value['name'],
    };
}

