/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystemParameterModel
 */
export interface RatingSystemParameterModel {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemParameterModel
     */
    ratingSystemParameterId: number;
    /**
     * 
     * @type {number}
     * @memberof RatingSystemParameterModel
     */
    ratingSystemId: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemParameterModel
     */
    parameterRatingMax: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemParameterModel
     */
    name: string;
}

/**
 * Check if a given object implements the RatingSystemParameterModel interface.
 */
export function instanceOfRatingSystemParameterModel(value: object): value is RatingSystemParameterModel {
    if (!('ratingSystemParameterId' in value) || value['ratingSystemParameterId'] === undefined) return false;
    if (!('ratingSystemId' in value) || value['ratingSystemId'] === undefined) return false;
    if (!('parameterRatingMax' in value) || value['parameterRatingMax'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RatingSystemParameterModelFromJSON(json: any): RatingSystemParameterModel {
    return RatingSystemParameterModelFromJSONTyped(json, false);
}

export function RatingSystemParameterModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemParameterModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ratingSystemParameterId': json['rating_system_parameter_id'],
        'ratingSystemId': json['rating_system_id'],
        'parameterRatingMax': json['parameter_rating_max'],
        'name': json['name'],
    };
}

export function RatingSystemParameterModelToJSON(json: any): RatingSystemParameterModel {
    return RatingSystemParameterModelToJSONTyped(json, false);
}

export function RatingSystemParameterModelToJSONTyped(value?: RatingSystemParameterModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_system_parameter_id': value['ratingSystemParameterId'],
        'rating_system_id': value['ratingSystemId'],
        'parameter_rating_max': value['parameterRatingMax'],
        'name': value['name'],
    };
}

