/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingSystemModel
 */
export interface RatingSystemModel {
    /**
     * 
     * @type {number}
     * @memberof RatingSystemModel
     */
    rating_system_id: number;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemModel
     */
    master_rating_type: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemModel
     */
    rating_max: string;
    /**
     * 
     * @type {string}
     * @memberof RatingSystemModel
     */
    name: string;
}

/**
 * Check if a given object implements the RatingSystemModel interface.
 */
export function instanceOfRatingSystemModel(value: object): value is RatingSystemModel {
    if (!('rating_system_id' in value) || value['rating_system_id'] === undefined) return false;
    if (!('master_rating_type' in value) || value['master_rating_type'] === undefined) return false;
    if (!('rating_max' in value) || value['rating_max'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RatingSystemModelFromJSON(json: any): RatingSystemModel {
    return RatingSystemModelFromJSONTyped(json, false);
}

export function RatingSystemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingSystemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rating_system_id': json['rating_system_id'],
        'master_rating_type': json['master_rating_type'],
        'rating_max': json['rating_max'],
        'name': json['name'],
    };
}

export function RatingSystemModelToJSON(json: any): RatingSystemModel {
    return RatingSystemModelToJSONTyped(json, false);
}

export function RatingSystemModelToJSONTyped(value?: RatingSystemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_system_id': value['rating_system_id'],
        'master_rating_type': value['master_rating_type'],
        'rating_max': value['rating_max'],
        'name': value['name'],
    };
}

