/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Recording } from './Recording';
import {
    RecordingFromJSON,
    RecordingFromJSONTyped,
    RecordingToJSON,
    RecordingToJSONTyped,
} from './Recording';

/**
 * 
 * @export
 * @interface RecordingSearchResponse
 */
export interface RecordingSearchResponse {
    /**
     * 
     * @type {string}
     * @memberof RecordingSearchResponse
     */
    created?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecordingSearchResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof RecordingSearchResponse
     */
    offset: number;
    /**
     * 
     * @type {Array<Recording>}
     * @memberof RecordingSearchResponse
     */
    recordings: Array<Recording>;
}

/**
 * Check if a given object implements the RecordingSearchResponse interface.
 */
export function instanceOfRecordingSearchResponse(value: object): value is RecordingSearchResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('recordings' in value) || value['recordings'] === undefined) return false;
    return true;
}

export function RecordingSearchResponseFromJSON(json: any): RecordingSearchResponse {
    return RecordingSearchResponseFromJSONTyped(json, false);
}

export function RecordingSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordingSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'count': json['count'],
        'offset': json['offset'],
        'recordings': ((json['recordings'] as Array<any>).map(RecordingFromJSON)),
    };
}

export function RecordingSearchResponseToJSON(json: any): RecordingSearchResponse {
    return RecordingSearchResponseToJSONTyped(json, false);
}

export function RecordingSearchResponseToJSONTyped(value?: RecordingSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'count': value['count'],
        'offset': value['offset'],
        'recordings': ((value['recordings'] as Array<any>).map(RecordingToJSON)),
    };
}

