/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Release } from './Release';
import {
    ReleaseFromJSON,
    ReleaseFromJSONTyped,
    ReleaseToJSON,
    ReleaseToJSONTyped,
} from './Release';
import type { ArtistCredit } from './ArtistCredit';
import {
    ArtistCreditFromJSON,
    ArtistCreditFromJSONTyped,
    ArtistCreditToJSON,
    ArtistCreditToJSONTyped,
} from './ArtistCredit';

/**
 * 
 * @export
 * @interface Recording
 */
export interface Recording {
    /**
     * 
     * @type {string}
     * @memberof Recording
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Recording
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof Recording
     */
    length?: number | null;
    /**
     * 
     * @type {Array<ArtistCredit>}
     * @memberof Recording
     */
    artist_credit?: Array<ArtistCredit> | null;
    /**
     * 
     * @type {Array<Release>}
     * @memberof Recording
     */
    releases?: Array<Release> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Recording
     */
    isrcs?: Array<string> | null;
}

/**
 * Check if a given object implements the Recording interface.
 */
export function instanceOfRecording(value: object): value is Recording {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function RecordingFromJSON(json: any): Recording {
    return RecordingFromJSONTyped(json, false);
}

export function RecordingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recording {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'length': json['length'] == null ? undefined : json['length'],
        'artist_credit': json['artist-credit'] == null ? undefined : ((json['artist-credit'] as Array<any>).map(ArtistCreditFromJSON)),
        'releases': json['releases'] == null ? undefined : ((json['releases'] as Array<any>).map(ReleaseFromJSON)),
        'isrcs': json['isrcs'] == null ? undefined : json['isrcs'],
    };
}

export function RecordingToJSON(json: any): Recording {
    return RecordingToJSONTyped(json, false);
}

export function RecordingToJSONTyped(value?: Recording | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'length': value['length'],
        'artist-credit': value['artist_credit'] == null ? undefined : ((value['artist_credit'] as Array<any>).map(ArtistCreditToJSON)),
        'releases': value['releases'] == null ? undefined : ((value['releases'] as Array<any>).map(ReleaseToJSON)),
        'isrcs': value['isrcs'],
    };
}

