/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReleaseGroup } from './ReleaseGroup';
import {
    ReleaseGroupFromJSON,
    ReleaseGroupFromJSONTyped,
    ReleaseGroupToJSON,
    ReleaseGroupToJSONTyped,
} from './ReleaseGroup';

/**
 * 
 * @export
 * @interface ReleaseGroupSearchResponse
 */
export interface ReleaseGroupSearchResponse {
    /**
     * 
     * @type {string}
     * @memberof ReleaseGroupSearchResponse
     */
    created?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReleaseGroupSearchResponse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ReleaseGroupSearchResponse
     */
    offset: number;
    /**
     * 
     * @type {Array<ReleaseGroup>}
     * @memberof ReleaseGroupSearchResponse
     */
    release_groups: Array<ReleaseGroup>;
}

/**
 * Check if a given object implements the ReleaseGroupSearchResponse interface.
 */
export function instanceOfReleaseGroupSearchResponse(value: object): value is ReleaseGroupSearchResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('release_groups' in value) || value['release_groups'] === undefined) return false;
    return true;
}

export function ReleaseGroupSearchResponseFromJSON(json: any): ReleaseGroupSearchResponse {
    return ReleaseGroupSearchResponseFromJSONTyped(json, false);
}

export function ReleaseGroupSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseGroupSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'count': json['count'],
        'offset': json['offset'],
        'release_groups': ((json['release-groups'] as Array<any>).map(ReleaseGroupFromJSON)),
    };
}

export function ReleaseGroupSearchResponseToJSON(json: any): ReleaseGroupSearchResponse {
    return ReleaseGroupSearchResponseToJSONTyped(json, false);
}

export function ReleaseGroupSearchResponseToJSONTyped(value?: ReleaseGroupSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'count': value['count'],
        'offset': value['offset'],
        'release-groups': ((value['release_groups'] as Array<any>).map(ReleaseGroupToJSON)),
    };
}

