/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelInfo } from './LabelInfo';
import {
    LabelInfoFromJSON,
    LabelInfoFromJSONTyped,
    LabelInfoToJSON,
    LabelInfoToJSONTyped,
} from './LabelInfo';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';
import type { ReleaseGroup } from './ReleaseGroup';
import {
    ReleaseGroupFromJSON,
    ReleaseGroupFromJSONTyped,
    ReleaseGroupToJSON,
    ReleaseGroupToJSONTyped,
} from './ReleaseGroup';
import type { ArtistCredit } from './ArtistCredit';
import {
    ArtistCreditFromJSON,
    ArtistCreditFromJSONTyped,
    ArtistCreditToJSON,
    ArtistCreditToJSONTyped,
} from './ArtistCredit';

/**
 * 
 * @export
 * @interface Release
 */
export interface Release {
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    date?: string | null;
    /**
     * 
     * @type {ReleaseGroup}
     * @memberof Release
     */
    release_group?: ReleaseGroup | null;
    /**
     * 
     * @type {Array<ArtistCredit>}
     * @memberof Release
     */
    artist_credit?: Array<ArtistCredit> | null;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    barcode?: string | null;
    /**
     * 
     * @type {Array<Media>}
     * @memberof Release
     */
    media?: Array<Media> | null;
    /**
     * 
     * @type {Array<LabelInfo>}
     * @memberof Release
     */
    label_info?: Array<LabelInfo> | null;
}

/**
 * Check if a given object implements the Release interface.
 */
export function instanceOfRelease(value: object): value is Release {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ReleaseFromJSON(json: any): Release {
    return ReleaseFromJSONTyped(json, false);
}

export function ReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Release {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'date': json['date'] == null ? undefined : json['date'],
        'release_group': json['release-group'] == null ? undefined : ReleaseGroupFromJSON(json['release-group']),
        'artist_credit': json['artist-credit'] == null ? undefined : ((json['artist-credit'] as Array<any>).map(ArtistCreditFromJSON)),
        'country': json['country'] == null ? undefined : json['country'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'media': json['media'] == null ? undefined : ((json['media'] as Array<any>).map(MediaFromJSON)),
        'label_info': json['label-info'] == null ? undefined : ((json['label-info'] as Array<any>).map(LabelInfoFromJSON)),
    };
}

export function ReleaseToJSON(json: any): Release {
    return ReleaseToJSONTyped(json, false);
}

export function ReleaseToJSONTyped(value?: Release | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'status': value['status'],
        'date': value['date'],
        'release-group': ReleaseGroupToJSON(value['release_group']),
        'artist-credit': value['artist_credit'] == null ? undefined : ((value['artist_credit'] as Array<any>).map(ArtistCreditToJSON)),
        'country': value['country'],
        'barcode': value['barcode'],
        'media': value['media'] == null ? undefined : ((value['media'] as Array<any>).map(MediaToJSON)),
        'label-info': value['label_info'] == null ? undefined : ((value['label_info'] as Array<any>).map(LabelInfoToJSON)),
    };
}

