/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Release } from './Release';
import {
    ReleaseFromJSON,
    ReleaseFromJSONTyped,
    ReleaseToJSON,
    ReleaseToJSONTyped,
} from './Release';
import type { ArtistCredit } from './ArtistCredit';
import {
    ArtistCreditFromJSON,
    ArtistCreditFromJSONTyped,
    ArtistCreditToJSON,
    ArtistCreditToJSONTyped,
} from './ArtistCredit';

/**
 * 
 * @export
 * @interface ReleaseGroup
 */
export interface ReleaseGroup {
    /**
     * 
     * @type {string}
     * @memberof ReleaseGroup
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ReleaseGroup
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReleaseGroup
     */
    primary_type?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReleaseGroup
     */
    secondary_types?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ReleaseGroup
     */
    first_release_date?: string | null;
    /**
     * 
     * @type {Array<ArtistCredit>}
     * @memberof ReleaseGroup
     */
    artist_credit?: Array<ArtistCredit> | null;
    /**
     * 
     * @type {Array<Release>}
     * @memberof ReleaseGroup
     */
    releases?: Array<Release> | null;
}

/**
 * Check if a given object implements the ReleaseGroup interface.
 */
export function instanceOfReleaseGroup(value: object): value is ReleaseGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ReleaseGroupFromJSON(json: any): ReleaseGroup {
    return ReleaseGroupFromJSONTyped(json, false);
}

export function ReleaseGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'primary_type': json['primary-type'] == null ? undefined : json['primary-type'],
        'secondary_types': json['secondary-types'] == null ? undefined : json['secondary-types'],
        'first_release_date': json['first-release-date'] == null ? undefined : json['first-release-date'],
        'artist_credit': json['artist-credit'] == null ? undefined : ((json['artist-credit'] as Array<any>).map(ArtistCreditFromJSON)),
        'releases': json['releases'] == null ? undefined : ((json['releases'] as Array<any>).map(ReleaseFromJSON)),
    };
}

export function ReleaseGroupToJSON(json: any): ReleaseGroup {
    return ReleaseGroupToJSONTyped(json, false);
}

export function ReleaseGroupToJSONTyped(value?: ReleaseGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'primary-type': value['primary_type'],
        'secondary-types': value['secondary_types'],
        'first-release-date': value['first_release_date'],
        'artist-credit': value['artist_credit'] == null ? undefined : ((value['artist_credit'] as Array<any>).map(ArtistCreditToJSON)),
        'releases': value['releases'] == null ? undefined : ((value['releases'] as Array<any>).map(ReleaseToJSON)),
    };
}

