/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface SignInResponse
 */
export interface SignInResponse {
    /**
     * 
     * @type {string}
     * @memberof SignInResponse
     */
    pulsarr_api_key: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof SignInResponse
     */
    user: UserDTO;
}

/**
 * Check if a given object implements the SignInResponse interface.
 */
export function instanceOfSignInResponse(value: object): value is SignInResponse {
    if (!('pulsarr_api_key' in value) || value['pulsarr_api_key'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function SignInResponseFromJSON(json: any): SignInResponse {
    return SignInResponseFromJSONTyped(json, false);
}

export function SignInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pulsarr_api_key': json['pulsarr_api_key'],
        'user': UserDTOFromJSON(json['user']),
    };
}

export function SignInResponseToJSON(json: any): SignInResponse {
    return SignInResponseToJSONTyped(json, false);
}

export function SignInResponseToJSONTyped(value?: SignInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pulsarr_api_key': value['pulsarr_api_key'],
        'user': UserDTOToJSON(value['user']),
    };
}

