/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Recording } from './Recording';
import {
    RecordingFromJSON,
    RecordingFromJSONTyped,
    RecordingToJSON,
    RecordingToJSONTyped,
} from './Recording';

/**
 * 
 * @export
 * @interface Track
 */
export interface Track {
    /**
     * 
     * @type {string}
     * @memberof Track
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Track
     */
    number?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Track
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof Track
     */
    length?: number | null;
    /**
     * 
     * @type {Recording}
     * @memberof Track
     */
    recording?: Recording | null;
}

/**
 * Check if a given object implements the Track interface.
 */
export function instanceOfTrack(value: object): value is Track {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TrackFromJSON(json: any): Track {
    return TrackFromJSONTyped(json, false);
}

export function TrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Track {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'number': json['number'] == null ? undefined : json['number'],
        'title': json['title'],
        'length': json['length'] == null ? undefined : json['length'],
        'recording': json['recording'] == null ? undefined : RecordingFromJSON(json['recording']),
    };
}

export function TrackToJSON(json: any): Track {
    return TrackToJSONTyped(json, false);
}

export function TrackToJSONTyped(value?: Track | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'number': value['number'],
        'title': value['title'],
        'length': value['length'],
        'recording': RecordingToJSON(value['recording']),
    };
}

