/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtistCount } from './ArtistCount';
import {
    ArtistCountFromJSON,
    ArtistCountFromJSONTyped,
    ArtistCountToJSON,
    ArtistCountToJSONTyped,
} from './ArtistCount';

/**
 * 
 * @export
 * @interface UserRatingStats
 */
export interface UserRatingStats {
    /**
     * 
     * @type {number}
     * @memberof UserRatingStats
     */
    total_ratings: number;
    /**
     * 
     * @type {string}
     * @memberof UserRatingStats
     */
    average_rating?: string | null;
    /**
     * 
     * @type {Array<ArtistCount>}
     * @memberof UserRatingStats
     */
    top_artists: Array<ArtistCount>;
}

/**
 * Check if a given object implements the UserRatingStats interface.
 */
export function instanceOfUserRatingStats(value: object): value is UserRatingStats {
    if (!('total_ratings' in value) || value['total_ratings'] === undefined) return false;
    if (!('top_artists' in value) || value['top_artists'] === undefined) return false;
    return true;
}

export function UserRatingStatsFromJSON(json: any): UserRatingStats {
    return UserRatingStatsFromJSONTyped(json, false);
}

export function UserRatingStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRatingStats {
    if (json == null) {
        return json;
    }
    return {
        
        'total_ratings': json['total_ratings'],
        'average_rating': json['average_rating'] == null ? undefined : json['average_rating'],
        'top_artists': ((json['top_artists'] as Array<any>).map(ArtistCountFromJSON)),
    };
}

export function UserRatingStatsToJSON(json: any): UserRatingStats {
    return UserRatingStatsToJSONTyped(json, false);
}

export function UserRatingStatsToJSONTyped(value?: UserRatingStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_ratings': value['total_ratings'],
        'average_rating': value['average_rating'],
        'top_artists': ((value['top_artists'] as Array<any>).map(ArtistCountToJSON)),
    };
}

