/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';
import type { GroupDTO } from './GroupDTO';
import {
    GroupDTOFromJSON,
    GroupDTOFromJSONTyped,
    GroupDTOToJSON,
    GroupDTOToJSONTyped,
} from './GroupDTO';

/**
 * 
 * @export
 * @interface UserProfileResponse
 */
export interface UserProfileResponse {
    /**
     * 
     * @type {UserDTO}
     * @memberof UserProfileResponse
     */
    user: UserDTO;
    /**
     * 
     * @type {GroupDTO}
     * @memberof UserProfileResponse
     */
    crate_group?: GroupDTO | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserProfileResponse
     */
    visible_group_ids: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileResponse
     */
    is_own_profile: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileResponse
     */
    is_private: boolean;
}

/**
 * Check if a given object implements the UserProfileResponse interface.
 */
export function instanceOfUserProfileResponse(value: object): value is UserProfileResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('visible_group_ids' in value) || value['visible_group_ids'] === undefined) return false;
    if (!('is_own_profile' in value) || value['is_own_profile'] === undefined) return false;
    if (!('is_private' in value) || value['is_private'] === undefined) return false;
    return true;
}

export function UserProfileResponseFromJSON(json: any): UserProfileResponse {
    return UserProfileResponseFromJSONTyped(json, false);
}

export function UserProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserDTOFromJSON(json['user']),
        'crate_group': json['crate_group'] == null ? undefined : GroupDTOFromJSON(json['crate_group']),
        'visible_group_ids': json['visible_group_ids'],
        'is_own_profile': json['is_own_profile'],
        'is_private': json['is_private'],
    };
}

export function UserProfileResponseToJSON(json: any): UserProfileResponse {
    return UserProfileResponseToJSONTyped(json, false);
}

export function UserProfileResponseToJSONTyped(value?: UserProfileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserDTOToJSON(value['user']),
        'crate_group': GroupDTOToJSON(value['crate_group']),
        'visible_group_ids': value['visible_group_ids'],
        'is_own_profile': value['is_own_profile'],
        'is_private': value['is_private'],
    };
}

