/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateTokenResponse
 */
export interface ValidateTokenResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ValidateTokenResponse
     */
    valid: boolean;
}

/**
 * Check if a given object implements the ValidateTokenResponse interface.
 */
export function instanceOfValidateTokenResponse(value: object): value is ValidateTokenResponse {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    return true;
}

export function ValidateTokenResponseFromJSON(json: any): ValidateTokenResponse {
    return ValidateTokenResponseFromJSONTyped(json, false);
}

export function ValidateTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'],
    };
}

export function ValidateTokenResponseToJSON(json: any): ValidateTokenResponse {
    return ValidateTokenResponseToJSONTyped(json, false);
}

export function ValidateTokenResponseToJSONTyped(value?: ValidateTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
    };
}

