/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateTokenRequest
 */
export interface ValidateTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof ValidateTokenRequest
     */
    token: string;
}

/**
 * Check if a given object implements the ValidateTokenRequest interface.
 */
export function instanceOfValidateTokenRequest(value: object): value is ValidateTokenRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ValidateTokenRequestFromJSON(json: any): ValidateTokenRequest {
    return ValidateTokenRequestFromJSONTyped(json, false);
}

export function ValidateTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ValidateTokenRequestToJSON(json: any): ValidateTokenRequest {
    return ValidateTokenRequestToJSONTyped(json, false);
}

export function ValidateTokenRequestToJSONTyped(value?: ValidateTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

