/* tslint:disable */
/* eslint-disable */
/**
 * pulsarr_fulcrum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Work
 */
export interface Work {
    /**
     * 
     * @type {string}
     * @memberof Work
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Work
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Work
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Work
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Work
     */
    disambiguation?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Work
     */
    iswcs?: Array<string> | null;
}

/**
 * Check if a given object implements the Work interface.
 */
export function instanceOfWork(value: object): value is Work {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function WorkFromJSON(json: any): Work {
    return WorkFromJSONTyped(json, false);
}

export function WorkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Work {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'language': json['language'] == null ? undefined : json['language'],
        'disambiguation': json['disambiguation'] == null ? undefined : json['disambiguation'],
        'iswcs': json['iswcs'] == null ? undefined : json['iswcs'],
    };
}

export function WorkToJSON(json: any): Work {
    return WorkToJSONTyped(json, false);
}

export function WorkToJSONTyped(value?: Work | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'type': value['type'],
        'language': value['language'],
        'disambiguation': value['disambiguation'],
        'iswcs': value['iswcs'],
    };
}

