//
// ArtistCredit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArtistCredit: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var artist: Artist?

    public init(name: String? = nil, artist: Artist? = nil) {
        self.name = name
        self.artist = artist
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case artist
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(artist, forKey: .artist)
    }
}

