//
// GetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRequest: Codable, JSONEncodable, Hashable {

    public var takeSize: Int?

    public init(takeSize: Int? = nil) {
        self.takeSize = takeSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case takeSize = "take_size"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(takeSize, forKey: .takeSize)
    }
}

