//
// GroupMemberDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GroupMemberDTO: Codable, JSONEncodable, Hashable {

    public var pulsarrGroupId: Int
    public var user: UserDTO
    public var groupRole: String
    public var joinDate: String

    public init(pulsarrGroupId: Int, user: UserDTO, groupRole: String, joinDate: String) {
        self.pulsarrGroupId = pulsarrGroupId
        self.user = user
        self.groupRole = groupRole
        self.joinDate = joinDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pulsarrGroupId = "pulsarr_group_id"
        case user
        case groupRole = "group_role"
        case joinDate = "join_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pulsarrGroupId, forKey: .pulsarrGroupId)
        try container.encode(user, forKey: .user)
        try container.encode(groupRole, forKey: .groupRole)
        try container.encode(joinDate, forKey: .joinDate)
    }
}

