//
// GroupDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GroupDTO: Codable, JSONEncodable, Hashable {

    public var pulsarrGroupId: Int
    public var ratingSystemId: Int
    public var name: String
    public var privacyType: String
    public var ratingSystem: RatingSystemDTO?
    public var createdByUserId: Int?
    public var creationDate: String?
    public var members: [GroupMemberDTO]?

    public init(pulsarrGroupId: Int, ratingSystemId: Int, name: String, privacyType: String, ratingSystem: RatingSystemDTO? = nil, createdByUserId: Int? = nil, creationDate: String? = nil, members: [GroupMemberDTO]? = nil) {
        self.pulsarrGroupId = pulsarrGroupId
        self.ratingSystemId = ratingSystemId
        self.name = name
        self.privacyType = privacyType
        self.ratingSystem = ratingSystem
        self.createdByUserId = createdByUserId
        self.creationDate = creationDate
        self.members = members
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pulsarrGroupId = "pulsarr_group_id"
        case ratingSystemId = "rating_system_id"
        case name
        case privacyType = "privacy_type"
        case ratingSystem = "rating_system"
        case createdByUserId = "created_by_user_id"
        case creationDate = "creation_date"
        case members
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pulsarrGroupId, forKey: .pulsarrGroupId)
        try container.encode(ratingSystemId, forKey: .ratingSystemId)
        try container.encode(name, forKey: .name)
        try container.encode(privacyType, forKey: .privacyType)
        try container.encodeIfPresent(ratingSystem, forKey: .ratingSystem)
        try container.encodeIfPresent(createdByUserId, forKey: .createdByUserId)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(members, forKey: .members)
    }
}

