//
// RatingDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatingDetail: Codable, JSONEncodable, Hashable {

    public static let ratingValueRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^-?[0-9]+(\\.[0-9]+)?$/")
    public var ratingDetailId: Int
    public var ratingId: Int
    public var ratingSystemParameterId: Int
    public var ratingValue: String

    public init(ratingDetailId: Int, ratingId: Int, ratingSystemParameterId: Int, ratingValue: String) {
        self.ratingDetailId = ratingDetailId
        self.ratingId = ratingId
        self.ratingSystemParameterId = ratingSystemParameterId
        self.ratingValue = ratingValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ratingDetailId = "rating_detail_id"
        case ratingId = "rating_id"
        case ratingSystemParameterId = "rating_system_parameter_id"
        case ratingValue = "rating_value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ratingDetailId, forKey: .ratingDetailId)
        try container.encode(ratingId, forKey: .ratingId)
        try container.encode(ratingSystemParameterId, forKey: .ratingSystemParameterId)
        try container.encode(ratingValue, forKey: .ratingValue)
    }
}

