//
// RatingSystemDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatingSystemDTO: Codable, JSONEncodable, Hashable {

    public static let ratingMaxRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^-?[0-9]+(\\.[0-9]+)?$/")
    public var ratingSystemId: Int
    public var masterRatingType: String
    public var ratingMax: String
    public var name: String
    public var parameters: [RatingSystemParameterDTO]

    public init(ratingSystemId: Int, masterRatingType: String, ratingMax: String, name: String, parameters: [RatingSystemParameterDTO]) {
        self.ratingSystemId = ratingSystemId
        self.masterRatingType = masterRatingType
        self.ratingMax = ratingMax
        self.name = name
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ratingSystemId = "rating_system_id"
        case masterRatingType = "master_rating_type"
        case ratingMax = "rating_max"
        case name
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ratingSystemId, forKey: .ratingSystemId)
        try container.encode(masterRatingType, forKey: .masterRatingType)
        try container.encode(ratingMax, forKey: .ratingMax)
        try container.encode(name, forKey: .name)
        try container.encode(parameters, forKey: .parameters)
    }
}

