//
// RatingSystemParameterDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RatingSystemParameterDTO: Codable, JSONEncodable, Hashable {

    public static let parameterRatingMaxRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^-?[0-9]+(\\.[0-9]+)?$/")
    public var ratingSystemParameterId: Int
    public var ratingSystemId: Int
    public var parameterRatingMax: String
    public var name: String

    public init(ratingSystemParameterId: Int, ratingSystemId: Int, parameterRatingMax: String, name: String) {
        self.ratingSystemParameterId = ratingSystemParameterId
        self.ratingSystemId = ratingSystemId
        self.parameterRatingMax = parameterRatingMax
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ratingSystemParameterId = "rating_system_parameter_id"
        case ratingSystemId = "rating_system_id"
        case parameterRatingMax = "parameter_rating_max"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ratingSystemParameterId, forKey: .ratingSystemParameterId)
        try container.encode(ratingSystemId, forKey: .ratingSystemId)
        try container.encode(parameterRatingMax, forKey: .parameterRatingMax)
        try container.encode(name, forKey: .name)
    }
}

