//
// Rating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Rating: Codable, JSONEncodable, Hashable {

    public static let ratingValueRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^-?[0-9]+(\\.[0-9]+)?$/")
    public var ratingId: Int
    public var pulsarrUserId: Int
    public var pulsarrGroupId: Int
    public var ratingSystemId: Int
    public var comments: String
    public var ratingValue: String

    public init(ratingId: Int, pulsarrUserId: Int, pulsarrGroupId: Int, ratingSystemId: Int, comments: String, ratingValue: String) {
        self.ratingId = ratingId
        self.pulsarrUserId = pulsarrUserId
        self.pulsarrGroupId = pulsarrGroupId
        self.ratingSystemId = ratingSystemId
        self.comments = comments
        self.ratingValue = ratingValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ratingId = "rating_id"
        case pulsarrUserId = "pulsarr_user_id"
        case pulsarrGroupId = "pulsarr_group_id"
        case ratingSystemId = "rating_system_id"
        case comments
        case ratingValue = "rating_value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ratingId, forKey: .ratingId)
        try container.encode(pulsarrUserId, forKey: .pulsarrUserId)
        try container.encode(pulsarrGroupId, forKey: .pulsarrGroupId)
        try container.encode(ratingSystemId, forKey: .ratingSystemId)
        try container.encode(comments, forKey: .comments)
        try container.encode(ratingValue, forKey: .ratingValue)
    }
}

