//
// Recording.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Recording: Codable, JSONEncodable, Hashable {

    public static let lengthRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: String
    public var title: String
    public var length: Int?
    public var artistCredit: [ArtistCredit]?

    public init(id: String, title: String, length: Int? = nil, artistCredit: [ArtistCredit]? = nil) {
        self.id = id
        self.title = title
        self.length = length
        self.artistCredit = artistCredit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case length
        case artistCredit = "artist-credit"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(artistCredit, forKey: .artistCredit)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Recording: Identifiable {}
