//
// SignInResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignInResponse: Codable, JSONEncodable, Hashable {

    public var pulsarrApiKey: String
    public var user: UserDTO

    public init(pulsarrApiKey: String, user: UserDTO) {
        self.pulsarrApiKey = pulsarrApiKey
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pulsarrApiKey = "pulsarr_api_key"
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pulsarrApiKey, forKey: .pulsarrApiKey)
        try container.encode(user, forKey: .user)
    }
}

