//
// SignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request/response guards */
public struct SignInRequest: Codable, JSONEncodable, Hashable {

    public var username: String
    public var password: String
    public var hwKey: String

    public init(username: String, password: String, hwKey: String) {
        self.username = username
        self.password = password
        self.hwKey = hwKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
        case hwKey = "hw_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
        try container.encode(hwKey, forKey: .hwKey)
    }
}

