//
// ArtistSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArtistSearchResponse: Codable, JSONEncodable, Hashable {

    public static let countRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let offsetRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var created: String?
    public var count: Int
    public var offset: Int
    public var artists: [Artist]

    public init(created: String? = nil, count: Int, offset: Int, artists: [Artist]) {
        self.created = created
        self.count = count
        self.offset = offset
        self.artists = artists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case created
        case count
        case offset
        case artists
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encode(count, forKey: .count)
        try container.encode(offset, forKey: .offset)
        try container.encode(artists, forKey: .artists)
    }
}

