//
// Artist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Artist: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var sortName: String?
    public var type: String?
    public var disambiguation: String?
    public var country: String?
    public var lifeSpan: LifeSpan?
    public var releases: [Release]?
    public var releaseGroups: [ReleaseGroup]?
    public var recordings: [Recording]?
    public var works: [Work]?

    public init(id: String, name: String, sortName: String? = nil, type: String? = nil, disambiguation: String? = nil, country: String? = nil, lifeSpan: LifeSpan? = nil, releases: [Release]? = nil, releaseGroups: [ReleaseGroup]? = nil, recordings: [Recording]? = nil, works: [Work]? = nil) {
        self.id = id
        self.name = name
        self.sortName = sortName
        self.type = type
        self.disambiguation = disambiguation
        self.country = country
        self.lifeSpan = lifeSpan
        self.releases = releases
        self.releaseGroups = releaseGroups
        self.recordings = recordings
        self.works = works
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case sortName = "sort-name"
        case type
        case disambiguation
        case country
        case lifeSpan = "life-span"
        case releases
        case releaseGroups = "release-groups"
        case recordings
        case works
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(sortName, forKey: .sortName)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(disambiguation, forKey: .disambiguation)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(lifeSpan, forKey: .lifeSpan)
        try container.encodeIfPresent(releases, forKey: .releases)
        try container.encodeIfPresent(releaseGroups, forKey: .releaseGroups)
        try container.encodeIfPresent(recordings, forKey: .recordings)
        try container.encodeIfPresent(works, forKey: .works)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Artist: Identifiable {}
