//
// CoverArtThumbnails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoverArtThumbnails: Codable, JSONEncodable, Hashable {

    public var _250: String?
    public var _500: String?
    public var _1200: String?
    public var small: String?
    public var large: String?

    public init(_250: String? = nil, _500: String? = nil, _1200: String? = nil, small: String? = nil, large: String? = nil) {
        self._250 = _250
        self._500 = _500
        self._1200 = _1200
        self.small = small
        self.large = large
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _250 = "250"
        case _500 = "500"
        case _1200 = "1200"
        case small
        case large
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_250, forKey: ._250)
        try container.encodeIfPresent(_500, forKey: ._500)
        try container.encodeIfPresent(_1200, forKey: ._1200)
        try container.encodeIfPresent(small, forKey: .small)
        try container.encodeIfPresent(large, forKey: .large)
    }
}

