//
// CoverArtInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoverArtInfo: Codable, JSONEncodable, Hashable {

    public var front: String?
    public var back: String?
    public var frontThumbnailSmall: String?
    public var frontThumbnailLarge: String?
    public var backThumbnailSmall: String?
    public var backThumbnailLarge: String?
    public var allImages: [CoverArtImage]

    public init(front: String? = nil, back: String? = nil, frontThumbnailSmall: String? = nil, frontThumbnailLarge: String? = nil, backThumbnailSmall: String? = nil, backThumbnailLarge: String? = nil, allImages: [CoverArtImage]) {
        self.front = front
        self.back = back
        self.frontThumbnailSmall = frontThumbnailSmall
        self.frontThumbnailLarge = frontThumbnailLarge
        self.backThumbnailSmall = backThumbnailSmall
        self.backThumbnailLarge = backThumbnailLarge
        self.allImages = allImages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case front
        case back
        case frontThumbnailSmall = "front_thumbnail_small"
        case frontThumbnailLarge = "front_thumbnail_large"
        case backThumbnailSmall = "back_thumbnail_small"
        case backThumbnailLarge = "back_thumbnail_large"
        case allImages = "all_images"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(front, forKey: .front)
        try container.encodeIfPresent(back, forKey: .back)
        try container.encodeIfPresent(frontThumbnailSmall, forKey: .frontThumbnailSmall)
        try container.encodeIfPresent(frontThumbnailLarge, forKey: .frontThumbnailLarge)
        try container.encodeIfPresent(backThumbnailSmall, forKey: .backThumbnailSmall)
        try container.encodeIfPresent(backThumbnailLarge, forKey: .backThumbnailLarge)
        try container.encode(allImages, forKey: .allImages)
    }
}

