//
// CoverArtArchive.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoverArtArchive: Codable, JSONEncodable, Hashable {

    public var images: [CoverArtImage]
    public var release: String

    public init(images: [CoverArtImage], release: String) {
        self.images = images
        self.release = release
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case images
        case release
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(images, forKey: .images)
        try container.encode(release, forKey: .release)
    }
}

