//
// CoverArtImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CoverArtImage: Codable, JSONEncodable, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let editRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int
    public var image: String
    public var thumbnails: CoverArtThumbnails?
    public var front: Bool
    public var back: Bool
    public var types: [String]
    public var comment: String?
    public var approved: Bool?
    public var edit: Int?

    public init(id: Int, image: String, thumbnails: CoverArtThumbnails? = nil, front: Bool, back: Bool, types: [String], comment: String? = nil, approved: Bool? = nil, edit: Int? = nil) {
        self.id = id
        self.image = image
        self.thumbnails = thumbnails
        self.front = front
        self.back = back
        self.types = types
        self.comment = comment
        self.approved = approved
        self.edit = edit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case image
        case thumbnails
        case front
        case back
        case types
        case comment
        case approved
        case edit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(image, forKey: .image)
        try container.encodeIfPresent(thumbnails, forKey: .thumbnails)
        try container.encode(front, forKey: .front)
        try container.encode(back, forKey: .back)
        try container.encode(types, forKey: .types)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encodeIfPresent(approved, forKey: .approved)
        try container.encodeIfPresent(edit, forKey: .edit)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CoverArtImage: Identifiable {}
