//
// Label.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Label: Codable, JSONEncodable, Hashable {

    public static let labelCodeRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: String
    public var name: String
    public var sortName: String?
    public var labelCode: Int?
    public var type: String?
    public var disambiguation: String?
    public var country: String?
    public var lifeSpan: LifeSpan?

    public init(id: String, name: String, sortName: String? = nil, labelCode: Int? = nil, type: String? = nil, disambiguation: String? = nil, country: String? = nil, lifeSpan: LifeSpan? = nil) {
        self.id = id
        self.name = name
        self.sortName = sortName
        self.labelCode = labelCode
        self.type = type
        self.disambiguation = disambiguation
        self.country = country
        self.lifeSpan = lifeSpan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case sortName = "sort-name"
        case labelCode = "label-code"
        case type
        case disambiguation
        case country
        case lifeSpan = "life-span"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(sortName, forKey: .sortName)
        try container.encodeIfPresent(labelCode, forKey: .labelCode)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(disambiguation, forKey: .disambiguation)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(lifeSpan, forKey: .lifeSpan)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Label: Identifiable {}
