//
// LabelInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LabelInfo: Codable, JSONEncodable, Hashable {

    public var catalogNumber: String?
    public var label: Label?

    public init(catalogNumber: String? = nil, label: Label? = nil) {
        self.catalogNumber = catalogNumber
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case catalogNumber = "catalog-number"
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(catalogNumber, forKey: .catalogNumber)
        try container.encodeIfPresent(label, forKey: .label)
    }
}

