//
// LifeSpan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LifeSpan: Codable, JSONEncodable, Hashable {

    public var begin: String?
    public var end: String?
    public var ended: Bool?

    public init(begin: String? = nil, end: String? = nil, ended: Bool? = nil) {
        self.begin = begin
        self.end = end
        self.ended = ended
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case begin
        case end
        case ended
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(begin, forKey: .begin)
        try container.encodeIfPresent(end, forKey: .end)
        try container.encodeIfPresent(ended, forKey: .ended)
    }
}

