//
// Media.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Media: Codable, JSONEncodable, Hashable {

    public static let trackCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var format: String?
    public var trackCount: Int?
    public var tracks: [Track]?

    public init(format: String? = nil, trackCount: Int? = nil, tracks: [Track]? = nil) {
        self.format = format
        self.trackCount = trackCount
        self.tracks = tracks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case format
        case trackCount = "track-count"
        case tracks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(trackCount, forKey: .trackCount)
        try container.encodeIfPresent(tracks, forKey: .tracks)
    }
}

