//
// Release.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Release: Codable, JSONEncodable, Hashable {

    public var id: String
    public var title: String
    public var status: String?
    public var date: String?
    public var releaseGroup: ReleaseGroup?
    public var artistCredit: [ArtistCredit]?
    public var country: String?
    public var barcode: String?
    public var media: [Media]?
    public var labelInfo: [LabelInfo]?

    public init(id: String, title: String, status: String? = nil, date: String? = nil, releaseGroup: ReleaseGroup? = nil, artistCredit: [ArtistCredit]? = nil, country: String? = nil, barcode: String? = nil, media: [Media]? = nil, labelInfo: [LabelInfo]? = nil) {
        self.id = id
        self.title = title
        self.status = status
        self.date = date
        self.releaseGroup = releaseGroup
        self.artistCredit = artistCredit
        self.country = country
        self.barcode = barcode
        self.media = media
        self.labelInfo = labelInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case status
        case date
        case releaseGroup = "release-group"
        case artistCredit = "artist-credit"
        case country
        case barcode
        case media
        case labelInfo = "label-info"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(releaseGroup, forKey: .releaseGroup)
        try container.encodeIfPresent(artistCredit, forKey: .artistCredit)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(barcode, forKey: .barcode)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encodeIfPresent(labelInfo, forKey: .labelInfo)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Release: Identifiable {}
