//
// ReleaseGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReleaseGroup: Codable, JSONEncodable, Hashable {

    public var id: String
    public var title: String?
    public var primaryType: String?
    public var secondaryTypes: [String]?
    public var firstReleaseDate: String?
    public var artistCredit: [ArtistCredit]?
    public var releases: [Release]?

    public init(id: String, title: String? = nil, primaryType: String? = nil, secondaryTypes: [String]? = nil, firstReleaseDate: String? = nil, artistCredit: [ArtistCredit]? = nil, releases: [Release]? = nil) {
        self.id = id
        self.title = title
        self.primaryType = primaryType
        self.secondaryTypes = secondaryTypes
        self.firstReleaseDate = firstReleaseDate
        self.artistCredit = artistCredit
        self.releases = releases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case primaryType = "primary-type"
        case secondaryTypes = "secondary-types"
        case firstReleaseDate = "first-release-date"
        case artistCredit = "artist-credit"
        case releases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(primaryType, forKey: .primaryType)
        try container.encodeIfPresent(secondaryTypes, forKey: .secondaryTypes)
        try container.encodeIfPresent(firstReleaseDate, forKey: .firstReleaseDate)
        try container.encodeIfPresent(artistCredit, forKey: .artistCredit)
        try container.encodeIfPresent(releases, forKey: .releases)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ReleaseGroup: Identifiable {}
