//
// Track.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Track: Codable, JSONEncodable, Hashable {

    public static let lengthRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: String
    public var number: String?
    public var title: String
    public var length: Int?
    public var recording: Recording?

    public init(id: String, number: String? = nil, title: String, length: Int? = nil, recording: Recording? = nil) {
        self.id = id
        self.number = number
        self.title = title
        self.length = length
        self.recording = recording
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
        case title
        case length
        case recording
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(recording, forKey: .recording)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Track: Identifiable {}
