//
// Work.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Work: Codable, JSONEncodable, Hashable {

    public var id: String
    public var title: String
    public var type: String?
    public var language: String?
    public var disambiguation: String?
    public var iswcs: [String]?

    public init(id: String, title: String, type: String? = nil, language: String? = nil, disambiguation: String? = nil, iswcs: [String]? = nil) {
        self.id = id
        self.title = title
        self.type = type
        self.language = language
        self.disambiguation = disambiguation
        self.iswcs = iswcs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case type
        case language
        case disambiguation
        case iswcs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(disambiguation, forKey: .disambiguation)
        try container.encodeIfPresent(iswcs, forKey: .iswcs)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Work: Identifiable {}
