//
// RatingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RatingAPI {

    /**
     Add rating
     
     - parameter rating: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addRating(rating: Rating, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: Rating?, _ error: Error?) -> Void)) -> RequestTask {
        return addRatingWithRequestBuilder(rating: rating).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add rating
     - POST /rating/add
     - parameter rating: (body)  
     - returns: RequestBuilder<Rating> 
     */
    open class func addRatingWithRequestBuilder(rating: Rating) -> RequestBuilder<Rating> {
        let localVariablePath = "/rating/add"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rating)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Rating>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Add rating detail
     
     - parameter ratingDetail: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addRatingDetail(ratingDetail: RatingDetail, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: RatingDetail?, _ error: Error?) -> Void)) -> RequestTask {
        return addRatingDetailWithRequestBuilder(ratingDetail: ratingDetail).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add rating detail
     - POST /rating/rating_detail/add
     - parameter ratingDetail: (body)  
     - returns: RequestBuilder<RatingDetail> 
     */
    open class func addRatingDetailWithRequestBuilder(ratingDetail: RatingDetail) -> RequestBuilder<RatingDetail> {
        let localVariablePath = "/rating/rating_detail/add"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: ratingDetail)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RatingDetail>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Delete rating
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteRating(id: Int, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: Bool?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteRatingWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete rating
     - DELETE /rating/delete/{id}
     - parameter id: (path)  
     - returns: RequestBuilder<Bool> 
     */
    open class func deleteRatingWithRequestBuilder(id: Int) -> RequestBuilder<Bool> {
        var localVariablePath = "/rating/delete/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Bool>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Delete rating detail
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteRatingDetail(id: Int, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: Bool?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteRatingDetailWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete rating detail
     - DELETE /rating/rating_detail/delete/{id}
     - parameter id: (path)  
     - returns: RequestBuilder<Bool> 
     */
    open class func deleteRatingDetailWithRequestBuilder(id: Int) -> RequestBuilder<Bool> {
        var localVariablePath = "/rating/rating_detail/delete/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Bool>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get all rating details
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAllRatingDetails(apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: [RatingDetail]?, _ error: Error?) -> Void)) -> RequestTask {
        return getAllRatingDetailsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get all rating details
     - GET /rating/rating_detail
     - returns: RequestBuilder<[RatingDetail]> 
     */
    open class func getAllRatingDetailsWithRequestBuilder() -> RequestBuilder<[RatingDetail]> {
        let localVariablePath = "/rating/rating_detail"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RatingDetail]>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get all ratings
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAllRatings(apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Rating]?, _ error: Error?) -> Void)) -> RequestTask {
        return getAllRatingsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get all ratings
     - GET /rating/
     - returns: RequestBuilder<[Rating]> 
     */
    open class func getAllRatingsWithRequestBuilder() -> RequestBuilder<[Rating]> {
        let localVariablePath = "/rating/"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Rating]>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get a rating by id
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRating(id: Int, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: Rating?, _ error: Error?) -> Void)) -> RequestTask {
        return getRatingWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a rating by id
     - GET /rating/{id}
     - parameter id: (path)  
     - returns: RequestBuilder<Rating> 
     */
    open class func getRatingWithRequestBuilder(id: Int) -> RequestBuilder<Rating> {
        var localVariablePath = "/rating/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Rating>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get a rating detail by id
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRatingDetail(id: Int, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: RatingDetail?, _ error: Error?) -> Void)) -> RequestTask {
        return getRatingDetailWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a rating detail by id
     - GET /rating/rating_detail/{id}
     - parameter id: (path)  
     - returns: RequestBuilder<RatingDetail> 
     */
    open class func getRatingDetailWithRequestBuilder(id: Int) -> RequestBuilder<RatingDetail> {
        var localVariablePath = "/rating/rating_detail/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RatingDetail>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Update rating
     
     - parameter rating: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateRating(rating: Rating, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: Rating?, _ error: Error?) -> Void)) -> RequestTask {
        return updateRatingWithRequestBuilder(rating: rating).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update rating
     - POST /rating/update
     - parameter rating: (body)  
     - returns: RequestBuilder<Rating> 
     */
    open class func updateRatingWithRequestBuilder(rating: Rating) -> RequestBuilder<Rating> {
        let localVariablePath = "/rating/update"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rating)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Rating>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Update rating detail
     
     - parameter ratingDetail: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateRatingDetail(ratingDetail: RatingDetail, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: RatingDetail?, _ error: Error?) -> Void)) -> RequestTask {
        return updateRatingDetailWithRequestBuilder(ratingDetail: ratingDetail).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update rating detail
     - POST /rating/rating_detail/update
     - parameter ratingDetail: (body)  
     - returns: RequestBuilder<RatingDetail> 
     */
    open class func updateRatingDetailWithRequestBuilder(ratingDetail: RatingDetail) -> RequestBuilder<RatingDetail> {
        let localVariablePath = "/rating/rating_detail/update"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: ratingDetail)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RatingDetail>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
