//
// UserAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UserAPI {

    /**
     Add user
     
     - parameter userDTO: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addUser(userDTO: UserDTO, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: UserDTO?, _ error: Error?) -> Void)) -> RequestTask {
        return addUserWithRequestBuilder(userDTO: userDTO).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add user
     - POST /user/add
     - parameter userDTO: (body)  
     - returns: RequestBuilder<UserDTO> 
     */
    open class func addUserWithRequestBuilder(userDTO: UserDTO) -> RequestBuilder<UserDTO> {
        let localVariablePath = "/user/add"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userDTO)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserDTO>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Delete user
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteUser(id: Int, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: Bool?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteUserWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete user
     - DELETE /user/delete/{id}
     - parameter id: (path)  
     - returns: RequestBuilder<Bool> 
     */
    open class func deleteUserWithRequestBuilder(id: Int) -> RequestBuilder<Bool> {
        var localVariablePath = "/user/delete/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Bool>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get all users
     
     - parameter pulsarrApiKey: (header) Pulsarr Api Key (user session key) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAllUsers(pulsarrApiKey: String, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: [UserDTO]?, _ error: Error?) -> Void)) -> RequestTask {
        return getAllUsersWithRequestBuilder(pulsarrApiKey: pulsarrApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get all users
     - GET /user/
     - parameter pulsarrApiKey: (header) Pulsarr Api Key (user session key) 
     - returns: RequestBuilder<[UserDTO]> 
     */
    open class func getAllUsersWithRequestBuilder(pulsarrApiKey: String) -> RequestBuilder<[UserDTO]> {
        let localVariablePath = "/user/"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "pulsarr-api-key": pulsarrApiKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UserDTO]>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get a user by active session
     
     - parameter pulsarrApiKey: (header) Pulsarr Api Key (user session key) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCurrentUser(pulsarrApiKey: String, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: UserDTO?, _ error: Error?) -> Void)) -> RequestTask {
        return getCurrentUserWithRequestBuilder(pulsarrApiKey: pulsarrApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a user by active session
     - GET /user/currentUser
     - parameter pulsarrApiKey: (header) Pulsarr Api Key (user session key) 
     - returns: RequestBuilder<UserDTO> 
     */
    open class func getCurrentUserWithRequestBuilder(pulsarrApiKey: String) -> RequestBuilder<UserDTO> {
        let localVariablePath = "/user/currentUser"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "pulsarr-api-key": pulsarrApiKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserDTO>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get a user by id
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPulsarrUser(id: Int, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: UserDTO?, _ error: Error?) -> Void)) -> RequestTask {
        return getPulsarrUserWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a user by id
     - GET /user/{id}
     - parameter id: (path)  
     - returns: RequestBuilder<UserDTO> 
     */
    open class func getPulsarrUserWithRequestBuilder(id: Int) -> RequestBuilder<UserDTO> {
        var localVariablePath = "/user/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserDTO>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Update user
     
     - parameter userDTO: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateUser(userDTO: UserDTO, apiResponseQueue: DispatchQueue = PulsarrClientAPI.apiResponseQueue, completion: @escaping ((_ data: UserDTO?, _ error: Error?) -> Void)) -> RequestTask {
        return updateUserWithRequestBuilder(userDTO: userDTO).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update user
     - POST /user/update
     - parameter userDTO: (body)  
     - returns: RequestBuilder<UserDTO> 
     */
    open class func updateUserWithRequestBuilder(userDTO: UserDTO) -> RequestBuilder<UserDTO> {
        let localVariablePath = "/user/update"
        let localVariableURLString = PulsarrClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userDTO)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserDTO>.Type = PulsarrClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
